
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:07.821+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceEDOCSoap_BaroServiceEDOCSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_EDOC");

    private BaroServiceEDOCSoap_BaroServiceEDOCSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceEDOC.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceEDOC ss = new BaroServiceEDOC(wsdlURL, SERVICE_NAME);
        BaroServiceEDOCSoap port = ss.getBaroServiceEDOCSoap();

        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking cancelEDoc...");
        java.lang.String _cancelEDoc_certkey = "";
        java.lang.String _cancelEDoc_corpNum = "";
        java.lang.String _cancelEDoc_userID = "";
        java.lang.String _cancelEDoc_mgtKey = "";
        java.lang.String _cancelEDoc_memo = "";
        int _cancelEDoc__return = port.cancelEDoc(_cancelEDoc_certkey, _cancelEDoc_corpNum, _cancelEDoc_userID, _cancelEDoc_mgtKey, _cancelEDoc_memo);
        System.out.println("cancelEDoc.result=" + _cancelEDoc__return);


        }
        {
        System.out.println("Invoking removeDocLinkage...");
        java.lang.String _removeDocLinkage_certkey = "";
        java.lang.String _removeDocLinkage_corpNum = "";
        int _removeDocLinkage_fromDocType = 0;
        java.lang.String _removeDocLinkage_fromMgtKey = "";
        int _removeDocLinkage_toDocType = 0;
        java.lang.String _removeDocLinkage_toMgtKey = "";
        int _removeDocLinkage__return = port.removeDocLinkage(_removeDocLinkage_certkey, _removeDocLinkage_corpNum, _removeDocLinkage_fromDocType, _removeDocLinkage_fromMgtKey, _removeDocLinkage_toDocType, _removeDocLinkage_toMgtKey);
        System.out.println("removeDocLinkage.result=" + _removeDocLinkage__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking attachFileByFTP...");
        java.lang.String _attachFileByFTP_certkey = "";
        java.lang.String _attachFileByFTP_corpNum = "";
        java.lang.String _attachFileByFTP_userID = "";
        java.lang.String _attachFileByFTP_mgtKey = "";
        java.lang.String _attachFileByFTP_fileName = "";
        java.lang.String _attachFileByFTP_displayFileName = "";
        int _attachFileByFTP__return = port.attachFileByFTP(_attachFileByFTP_certkey, _attachFileByFTP_corpNum, _attachFileByFTP_userID, _attachFileByFTP_mgtKey, _attachFileByFTP_fileName, _attachFileByFTP_displayFileName);
        System.out.println("attachFileByFTP.result=" + _attachFileByFTP__return);


        }
        {
        System.out.println("Invoking registEDoc...");
        java.lang.String _registEDoc_certkey = "";
        java.lang.String _registEDoc_corpNum = "";
        java.lang.String _registEDoc_userID = "";
        com.baroservice.ws.EDoc _registEDoc_invoice = new com.baroservice.ws.EDoc();
        int _registEDoc__return = port.registEDoc(_registEDoc_certkey, _registEDoc_corpNum, _registEDoc_userID, _registEDoc_invoice);
        System.out.println("registEDoc.result=" + _registEDoc__return);


        }
        {
        System.out.println("Invoking issueEDoc...");
        java.lang.String _issueEDoc_certkey = "";
        java.lang.String _issueEDoc_corpNum = "";
        java.lang.String _issueEDoc_userID = "";
        java.lang.String _issueEDoc_mgtKey = "";
        boolean _issueEDoc_smsSendYN = false;
        java.lang.String _issueEDoc_memo = "";
        java.lang.String _issueEDoc_mailTitle = "";
        int _issueEDoc__return = port.issueEDoc(_issueEDoc_certkey, _issueEDoc_corpNum, _issueEDoc_userID, _issueEDoc_mgtKey, _issueEDoc_smsSendYN, _issueEDoc_memo, _issueEDoc_mailTitle);
        System.out.println("issueEDoc.result=" + _issueEDoc__return);


        }
        {
        System.out.println("Invoking deleteAttachFile...");
        java.lang.String _deleteAttachFile_certkey = "";
        java.lang.String _deleteAttachFile_corpNum = "";
        java.lang.String _deleteAttachFile_userID = "";
        java.lang.String _deleteAttachFile_mgtKey = "";
        int _deleteAttachFile__return = port.deleteAttachFile(_deleteAttachFile_certkey, _deleteAttachFile_corpNum, _deleteAttachFile_userID, _deleteAttachFile_mgtKey);
        System.out.println("deleteAttachFile.result=" + _deleteAttachFile__return);


        }
        {
        System.out.println("Invoking getBusinessLicenseRegistURL...");
        java.lang.String _getBusinessLicenseRegistURL_certkey = "";
        java.lang.String _getBusinessLicenseRegistURL_corpNum = "";
        java.lang.String _getBusinessLicenseRegistURL_userID = "";
        java.lang.String _getBusinessLicenseRegistURL_pwd = "";
        java.lang.String _getBusinessLicenseRegistURL__return = port.getBusinessLicenseRegistURL(_getBusinessLicenseRegistURL_certkey, _getBusinessLicenseRegistURL_corpNum, _getBusinessLicenseRegistURL_userID, _getBusinessLicenseRegistURL_pwd);
        System.out.println("getBusinessLicenseRegistURL.result=" + _getBusinessLicenseRegistURL__return);


        }
        {
        System.out.println("Invoking deleteEDoc...");
        java.lang.String _deleteEDoc_certkey = "";
        java.lang.String _deleteEDoc_corpNum = "";
        java.lang.String _deleteEDoc_userID = "";
        java.lang.String _deleteEDoc_mgtKey = "";
        int _deleteEDoc__return = port.deleteEDoc(_deleteEDoc_certkey, _deleteEDoc_corpNum, _deleteEDoc_userID, _deleteEDoc_mgtKey);
        System.out.println("deleteEDoc.result=" + _deleteEDoc__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking sendEmail2...");
        java.lang.String _sendEmail2_certkey = "";
        java.lang.String _sendEmail2_corpNum = "";
        java.lang.String _sendEmail2_userID = "";
        java.lang.String _sendEmail2_mgtKey = "";
        java.lang.String _sendEmail2_toEmailAddress = "";
        java.lang.String _sendEmail2_mailTitle = "";
        int _sendEmail2__return = port.sendEmail2(_sendEmail2_certkey, _sendEmail2_corpNum, _sendEmail2_userID, _sendEmail2_mgtKey, _sendEmail2_toEmailAddress, _sendEmail2_mailTitle);
        System.out.println("sendEmail2.result=" + _sendEmail2__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking checkIsValidEDoc...");
        java.lang.String _checkIsValidEDoc_certkey = "";
        java.lang.String _checkIsValidEDoc_corpNum = "";
        com.baroservice.ws.EDoc _checkIsValidEDoc_invoice = new com.baroservice.ws.EDoc();
        int _checkIsValidEDoc__return = port.checkIsValidEDoc(_checkIsValidEDoc_certkey, _checkIsValidEDoc_corpNum, _checkIsValidEDoc_invoice);
        System.out.println("checkIsValidEDoc.result=" + _checkIsValidEDoc__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getBankBookRegistURL...");
        java.lang.String _getBankBookRegistURL_certkey = "";
        java.lang.String _getBankBookRegistURL_corpNum = "";
        java.lang.String _getBankBookRegistURL_userID = "";
        java.lang.String _getBankBookRegistURL_pwd = "";
        java.lang.String _getBankBookRegistURL__return = port.getBankBookRegistURL(_getBankBookRegistURL_certkey, _getBankBookRegistURL_corpNum, _getBankBookRegistURL_userID, _getBankBookRegistURL_pwd);
        System.out.println("getBankBookRegistURL.result=" + _getBankBookRegistURL__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking updateEDoc...");
        java.lang.String _updateEDoc_certkey = "";
        java.lang.String _updateEDoc_corpNum = "";
        java.lang.String _updateEDoc_userID = "";
        com.baroservice.ws.EDoc _updateEDoc_invoice = new com.baroservice.ws.EDoc();
        int _updateEDoc__return = port.updateEDoc(_updateEDoc_certkey, _updateEDoc_corpNum, _updateEDoc_userID, _updateEDoc_invoice);
        System.out.println("updateEDoc.result=" + _updateEDoc__return);


        }
        {
        System.out.println("Invoking getEDocState...");
        java.lang.String _getEDocState_certkey = "";
        java.lang.String _getEDocState_corpNum = "";
        java.lang.String _getEDocState_userID = "";
        java.lang.String _getEDocState_mgtKey = "";
        com.baroservice.ws.EDocState _getEDocState__return = port.getEDocState(_getEDocState_certkey, _getEDocState_corpNum, _getEDocState_userID, _getEDocState_mgtKey);
        System.out.println("getEDocState.result=" + _getEDocState__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking getJicInRegistURL...");
        java.lang.String _getJicInRegistURL_certkey = "";
        java.lang.String _getJicInRegistURL_corpNum = "";
        java.lang.String _getJicInRegistURL_userID = "";
        java.lang.String _getJicInRegistURL_pwd = "";
        java.lang.String _getJicInRegistURL__return = port.getJicInRegistURL(_getJicInRegistURL_certkey, _getJicInRegistURL_corpNum, _getJicInRegistURL_userID, _getJicInRegistURL_pwd);
        System.out.println("getJicInRegistURL.result=" + _getJicInRegistURL__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getEDocStates...");
        java.lang.String _getEDocStates_certkey = "";
        java.lang.String _getEDocStates_corpNum = "";
        java.lang.String _getEDocStates_userID = "";
        com.baroservice.ws.ArrayOfString _getEDocStates_mgtKeyList = new com.baroservice.ws.ArrayOfString();
        com.baroservice.ws.ArrayOfEDocState _getEDocStates__return = port.getEDocStates(_getEDocStates_certkey, _getEDocStates_corpNum, _getEDocStates_userID, _getEDocStates_mgtKeyList);
        System.out.println("getEDocStates.result=" + _getEDocStates__return);


        }
        {
        System.out.println("Invoking getLinkedDocs...");
        java.lang.String _getLinkedDocs_certkey = "";
        java.lang.String _getLinkedDocs_corpNum = "";
        int _getLinkedDocs_docType = 0;
        java.lang.String _getLinkedDocs_mgtKey = "";
        com.baroservice.ws.ArrayOfLinkedDoc _getLinkedDocs__return = port.getLinkedDocs(_getLinkedDocs_certkey, _getLinkedDocs_corpNum, _getLinkedDocs_docType, _getLinkedDocs_mgtKey);
        System.out.println("getLinkedDocs.result=" + _getLinkedDocs__return);


        }
        {
        System.out.println("Invoking sendSMS...");
        java.lang.String _sendSMS_certkey = "";
        java.lang.String _sendSMS_corpNum = "";
        java.lang.String _sendSMS_userID = "";
        java.lang.String _sendSMS_mgtKey = "";
        java.lang.String _sendSMS_fromNumber = "";
        java.lang.String _sendSMS_toNumber = "";
        java.lang.String _sendSMS_contents = "";
        int _sendSMS__return = port.sendSMS(_sendSMS_certkey, _sendSMS_corpNum, _sendSMS_userID, _sendSMS_mgtKey, _sendSMS_fromNumber, _sendSMS_toNumber, _sendSMS_contents);
        System.out.println("sendSMS.result=" + _sendSMS__return);


        }
        {
        System.out.println("Invoking getEDocMailURL...");
        java.lang.String _getEDocMailURL_certkey = "";
        java.lang.String _getEDocMailURL_corpNum = "";
        java.lang.String _getEDocMailURL_userID = "";
        java.lang.String _getEDocMailURL_mgtKey = "";
        java.lang.String _getEDocMailURL__return = port.getEDocMailURL(_getEDocMailURL_certkey, _getEDocMailURL_corpNum, _getEDocMailURL_userID, _getEDocMailURL_mgtKey);
        System.out.println("getEDocMailURL.result=" + _getEDocMailURL__return);


        }
        {
        System.out.println("Invoking getEDocPopUpURL...");
        java.lang.String _getEDocPopUpURL_certkey = "";
        java.lang.String _getEDocPopUpURL_corpNum = "";
        java.lang.String _getEDocPopUpURL_userID = "";
        java.lang.String _getEDocPopUpURL_pwd = "";
        java.lang.String _getEDocPopUpURL_mgtKey = "";
        java.lang.String _getEDocPopUpURL__return = port.getEDocPopUpURL(_getEDocPopUpURL_certkey, _getEDocPopUpURL_corpNum, _getEDocPopUpURL_userID, _getEDocPopUpURL_pwd, _getEDocPopUpURL_mgtKey);
        System.out.println("getEDocPopUpURL.result=" + _getEDocPopUpURL__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking getEDocLog...");
        java.lang.String _getEDocLog_certkey = "";
        java.lang.String _getEDocLog_corpNum = "";
        java.lang.String _getEDocLog_userID = "";
        java.lang.String _getEDocLog_mgtKey = "";
        com.baroservice.ws.ArrayOfInvoiceLog _getEDocLog__return = port.getEDocLog(_getEDocLog_certkey, _getEDocLog_corpNum, _getEDocLog_userID, _getEDocLog_mgtKey);
        System.out.println("getEDocLog.result=" + _getEDocLog__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking getEDoc...");
        java.lang.String _getEDoc_certkey = "";
        java.lang.String _getEDoc_corpNum = "";
        java.lang.String _getEDoc_userID = "";
        java.lang.String _getEDoc_mgtKey = "";
        com.baroservice.ws.EDoc _getEDoc__return = port.getEDoc(_getEDoc_certkey, _getEDoc_corpNum, _getEDoc_userID, _getEDoc_mgtKey);
        System.out.println("getEDoc.result=" + _getEDoc__return);


        }
        {
        System.out.println("Invoking checkMgtKeyIsExists...");
        java.lang.String _checkMgtKeyIsExists_certkey = "";
        java.lang.String _checkMgtKeyIsExists_corpNum = "";
        java.lang.String _checkMgtKeyIsExists_userID = "";
        java.lang.String _checkMgtKeyIsExists_mgtKey = "";
        int _checkMgtKeyIsExists__return = port.checkMgtKeyIsExists(_checkMgtKeyIsExists_certkey, _checkMgtKeyIsExists_corpNum, _checkMgtKeyIsExists_userID, _checkMgtKeyIsExists_mgtKey);
        System.out.println("checkMgtKeyIsExists.result=" + _checkMgtKeyIsExists__return);


        }
        {
        System.out.println("Invoking makeDocLinkage...");
        java.lang.String _makeDocLinkage_certkey = "";
        java.lang.String _makeDocLinkage_corpNum = "";
        int _makeDocLinkage_fromDocType = 0;
        java.lang.String _makeDocLinkage_fromMgtKey = "";
        int _makeDocLinkage_toDocType = 0;
        java.lang.String _makeDocLinkage_toMgtKey = "";
        int _makeDocLinkage__return = port.makeDocLinkage(_makeDocLinkage_certkey, _makeDocLinkage_corpNum, _makeDocLinkage_fromDocType, _makeDocLinkage_fromMgtKey, _makeDocLinkage_toDocType, _makeDocLinkage_toMgtKey);
        System.out.println("makeDocLinkage.result=" + _makeDocLinkage__return);


        }
        {
        System.out.println("Invoking sendEmail...");
        java.lang.String _sendEmail_certkey = "";
        java.lang.String _sendEmail_corpNum = "";
        java.lang.String _sendEmail_userID = "";
        java.lang.String _sendEmail_mgtKey = "";
        java.lang.String _sendEmail_toEmailAddress = "";
        int _sendEmail__return = port.sendEmail(_sendEmail_certkey, _sendEmail_corpNum, _sendEmail_userID, _sendEmail_mgtKey, _sendEmail_toEmailAddress);
        System.out.println("sendEmail.result=" + _sendEmail__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getEDocPrintURL...");
        java.lang.String _getEDocPrintURL_certkey = "";
        java.lang.String _getEDocPrintURL_corpNum = "";
        java.lang.String _getEDocPrintURL_userID = "";
        java.lang.String _getEDocPrintURL_pwd = "";
        java.lang.String _getEDocPrintURL_mgtKey = "";
        java.lang.String _getEDocPrintURL__return = port.getEDocPrintURL(_getEDocPrintURL_certkey, _getEDocPrintURL_corpNum, _getEDocPrintURL_userID, _getEDocPrintURL_pwd, _getEDocPrintURL_mgtKey);
        System.out.println("getEDocPrintURL.result=" + _getEDocPrintURL__return);


        }
        {
        System.out.println("Invoking deleteAttachFileWithFileIndex...");
        java.lang.String _deleteAttachFileWithFileIndex_certkey = "";
        java.lang.String _deleteAttachFileWithFileIndex_corpNum = "";
        java.lang.String _deleteAttachFileWithFileIndex_userID = "";
        java.lang.String _deleteAttachFileWithFileIndex_mgtKey = "";
        int _deleteAttachFileWithFileIndex_fileIndex = 0;
        int _deleteAttachFileWithFileIndex__return = port.deleteAttachFileWithFileIndex(_deleteAttachFileWithFileIndex_certkey, _deleteAttachFileWithFileIndex_corpNum, _deleteAttachFileWithFileIndex_userID, _deleteAttachFileWithFileIndex_mgtKey, _deleteAttachFileWithFileIndex_fileIndex);
        System.out.println("deleteAttachFileWithFileIndex.result=" + _deleteAttachFileWithFileIndex__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getEDocsPrintURL...");
        java.lang.String _getEDocsPrintURL_certkey = "";
        java.lang.String _getEDocsPrintURL_corpNum = "";
        java.lang.String _getEDocsPrintURL_userID = "";
        java.lang.String _getEDocsPrintURL_pwd = "";
        com.baroservice.ws.ArrayOfString _getEDocsPrintURL_mgtKeyList = new com.baroservice.ws.ArrayOfString();
        java.lang.String _getEDocsPrintURL__return = port.getEDocsPrintURL(_getEDocsPrintURL_certkey, _getEDocsPrintURL_corpNum, _getEDocsPrintURL_userID, _getEDocsPrintURL_pwd, _getEDocsPrintURL_mgtKeyList);
        System.out.println("getEDocsPrintURL.result=" + _getEDocsPrintURL__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getAttachedFileList...");
        java.lang.String _getAttachedFileList_certkey = "";
        java.lang.String _getAttachedFileList_corpNum = "";
        java.lang.String _getAttachedFileList_userID = "";
        java.lang.String _getAttachedFileList_mgtKey = "";
        com.baroservice.ws.ArrayOfAttachedFile _getAttachedFileList__return = port.getAttachedFileList(_getAttachedFileList_certkey, _getAttachedFileList_corpNum, _getAttachedFileList_userID, _getAttachedFileList_mgtKey);
        System.out.println("getAttachedFileList.result=" + _getAttachedFileList__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking sendFax...");
        java.lang.String _sendFax_certkey = "";
        java.lang.String _sendFax_corpNum = "";
        java.lang.String _sendFax_userID = "";
        java.lang.String _sendFax_mgtKey = "";
        java.lang.String _sendFax_fromFaxNumber = "";
        java.lang.String _sendFax_toFaxNumber = "";
        int _sendFax__return = port.sendFax(_sendFax_certkey, _sendFax_corpNum, _sendFax_userID, _sendFax_mgtKey, _sendFax_fromFaxNumber, _sendFax_toFaxNumber);
        System.out.println("sendFax.result=" + _sendFax__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
