
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:40.658+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceFAXSoap_BaroServiceFAXSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_FAX");

    private BaroServiceFAXSoap_BaroServiceFAXSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceFAX.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceFAX ss = new BaroServiceFAX(wsdlURL, SERVICE_NAME);
        BaroServiceFAXSoap port = ss.getBaroServiceFAXSoap12();

        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking reSendFax...");
        java.lang.String _reSendFax_certkey = "";
        java.lang.String _reSendFax_corpNum = "";
        java.lang.String _reSendFax_senderID = "";
        java.lang.String _reSendFax_sendKey = "";
        java.lang.String _reSendFax_refKey = "";
        java.lang.String _reSendFax__return = port.reSendFax(_reSendFax_certkey, _reSendFax_corpNum, _reSendFax_senderID, _reSendFax_sendKey, _reSendFax_refKey);
        System.out.println("reSendFax.result=" + _reSendFax__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getFaxHistoryURL...");
        java.lang.String _getFaxHistoryURL_certkey = "";
        java.lang.String _getFaxHistoryURL_corpNum = "";
        java.lang.String _getFaxHistoryURL_id = "";
        java.lang.String _getFaxHistoryURL_pwd = "";
        java.lang.String _getFaxHistoryURL__return = port.getFaxHistoryURL(_getFaxHistoryURL_certkey, _getFaxHistoryURL_corpNum, _getFaxHistoryURL_id, _getFaxHistoryURL_pwd);
        System.out.println("getFaxHistoryURL.result=" + _getFaxHistoryURL__return);


        }
        {
        System.out.println("Invoking cancelReservedFaxMessage...");
        java.lang.String _cancelReservedFaxMessage_certkey = "";
        java.lang.String _cancelReservedFaxMessage_corpNum = "";
        java.lang.String _cancelReservedFaxMessage_sendKey = "";
        int _cancelReservedFaxMessage__return = port.cancelReservedFaxMessage(_cancelReservedFaxMessage_certkey, _cancelReservedFaxMessage_corpNum, _cancelReservedFaxMessage_sendKey);
        System.out.println("cancelReservedFaxMessage.result=" + _cancelReservedFaxMessage__return);


        }
        {
        System.out.println("Invoking sendFaxFromFTPEx...");
        java.lang.String _sendFaxFromFTPEx_certkey = "";
        java.lang.String _sendFaxFromFTPEx_corpNum = "";
        java.lang.String _sendFaxFromFTPEx_senderID = "";
        int _sendFaxFromFTPEx_fileCount = 0;
        com.baroservice.ws.ArrayOfString _sendFaxFromFTPEx_fileNames = new com.baroservice.ws.ArrayOfString();
        java.lang.String _sendFaxFromFTPEx_fromNumber = "";
        java.lang.String _sendFaxFromFTPEx_toNumber = "";
        java.lang.String _sendFaxFromFTPEx_receiveCorp = "";
        java.lang.String _sendFaxFromFTPEx_receiveName = "";
        java.lang.String _sendFaxFromFTPEx_sendDT = "";
        java.lang.String _sendFaxFromFTPEx_refKey = "";
        java.lang.String _sendFaxFromFTPEx__return = port.sendFaxFromFTPEx(_sendFaxFromFTPEx_certkey, _sendFaxFromFTPEx_corpNum, _sendFaxFromFTPEx_senderID, _sendFaxFromFTPEx_fileCount, _sendFaxFromFTPEx_fileNames, _sendFaxFromFTPEx_fromNumber, _sendFaxFromFTPEx_toNumber, _sendFaxFromFTPEx_receiveCorp, _sendFaxFromFTPEx_receiveName, _sendFaxFromFTPEx_sendDT, _sendFaxFromFTPEx_refKey);
        System.out.println("sendFaxFromFTPEx.result=" + _sendFaxFromFTPEx__return);


        }
        {
        System.out.println("Invoking getFaxMessage...");
        java.lang.String _getFaxMessage_certkey = "";
        java.lang.String _getFaxMessage_corpNum = "";
        java.lang.String _getFaxMessage_sendKey = "";
        com.baroservice.ws.FaxMessage _getFaxMessage__return = port.getFaxMessage(_getFaxMessage_certkey, _getFaxMessage_corpNum, _getFaxMessage_sendKey);
        System.out.println("getFaxMessage.result=" + _getFaxMessage__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getFaxSendMessagesByRefKey...");
        java.lang.String _getFaxSendMessagesByRefKey_certkey = "";
        java.lang.String _getFaxSendMessagesByRefKey_corpNum = "";
        java.lang.String _getFaxSendMessagesByRefKey_refKey = "";
        com.baroservice.ws.ArrayOfFaxMessage _getFaxSendMessagesByRefKey__return = port.getFaxSendMessagesByRefKey(_getFaxSendMessagesByRefKey_certkey, _getFaxSendMessagesByRefKey_corpNum, _getFaxSendMessagesByRefKey_refKey);
        System.out.println("getFaxSendMessagesByRefKey.result=" + _getFaxSendMessagesByRefKey__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking getFaxSendMessagesEx...");
        java.lang.String _getFaxSendMessagesEx_certkey = "";
        java.lang.String _getFaxSendMessagesEx_corpNum = "";
        com.baroservice.ws.ArrayOfString _getFaxSendMessagesEx_sendKeyList = new com.baroservice.ws.ArrayOfString();
        com.baroservice.ws.ArrayOfFaxMessageEx _getFaxSendMessagesEx__return = port.getFaxSendMessagesEx(_getFaxSendMessagesEx_certkey, _getFaxSendMessagesEx_corpNum, _getFaxSendMessagesEx_sendKeyList);
        System.out.println("getFaxSendMessagesEx.result=" + _getFaxSendMessagesEx__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking sendFaxesFromFTP...");
        java.lang.String _sendFaxesFromFTP_certkey = "";
        java.lang.String _sendFaxesFromFTP_corpNum = "";
        java.lang.String _sendFaxesFromFTP_senderID = "";
        java.lang.String _sendFaxesFromFTP_fileName = "";
        int _sendFaxesFromFTP_sendCount = 0;
        com.baroservice.ws.ArrayOfFaxMessage _sendFaxesFromFTP_messages = new com.baroservice.ws.ArrayOfFaxMessage();
        java.lang.String _sendFaxesFromFTP_sendDT = "";
        com.baroservice.ws.ArrayOfString _sendFaxesFromFTP__return = port.sendFaxesFromFTP(_sendFaxesFromFTP_certkey, _sendFaxesFromFTP_corpNum, _sendFaxesFromFTP_senderID, _sendFaxesFromFTP_fileName, _sendFaxesFromFTP_sendCount, _sendFaxesFromFTP_messages, _sendFaxesFromFTP_sendDT);
        System.out.println("sendFaxesFromFTP.result=" + _sendFaxesFromFTP__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking sendFaxesFromFTPEx...");
        java.lang.String _sendFaxesFromFTPEx_certkey = "";
        java.lang.String _sendFaxesFromFTPEx_corpNum = "";
        java.lang.String _sendFaxesFromFTPEx_senderID = "";
        int _sendFaxesFromFTPEx_fileCount = 0;
        com.baroservice.ws.ArrayOfString _sendFaxesFromFTPEx_fileNames = new com.baroservice.ws.ArrayOfString();
        int _sendFaxesFromFTPEx_sendCount = 0;
        com.baroservice.ws.ArrayOfFaxMessage _sendFaxesFromFTPEx_messages = new com.baroservice.ws.ArrayOfFaxMessage();
        java.lang.String _sendFaxesFromFTPEx_sendDT = "";
        com.baroservice.ws.ArrayOfString _sendFaxesFromFTPEx__return = port.sendFaxesFromFTPEx(_sendFaxesFromFTPEx_certkey, _sendFaxesFromFTPEx_corpNum, _sendFaxesFromFTPEx_senderID, _sendFaxesFromFTPEx_fileCount, _sendFaxesFromFTPEx_fileNames, _sendFaxesFromFTPEx_sendCount, _sendFaxesFromFTPEx_messages, _sendFaxesFromFTPEx_sendDT);
        System.out.println("sendFaxesFromFTPEx.result=" + _sendFaxesFromFTPEx__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking getFaxSendState...");
        java.lang.String _getFaxSendState_certkey = "";
        java.lang.String _getFaxSendState_corpNum = "";
        java.lang.String _getFaxSendState_sendKey = "";
        int _getFaxSendState__return = port.getFaxSendState(_getFaxSendState_certkey, _getFaxSendState_corpNum, _getFaxSendState_sendKey);
        System.out.println("getFaxSendState.result=" + _getFaxSendState__return);


        }
        {
        System.out.println("Invoking getFaxSendMessagesByRefKeyEx...");
        java.lang.String _getFaxSendMessagesByRefKeyEx_certkey = "";
        java.lang.String _getFaxSendMessagesByRefKeyEx_corpNum = "";
        java.lang.String _getFaxSendMessagesByRefKeyEx_refKey = "";
        com.baroservice.ws.ArrayOfFaxMessageEx _getFaxSendMessagesByRefKeyEx__return = port.getFaxSendMessagesByRefKeyEx(_getFaxSendMessagesByRefKeyEx_certkey, _getFaxSendMessagesByRefKeyEx_corpNum, _getFaxSendMessagesByRefKeyEx_refKey);
        System.out.println("getFaxSendMessagesByRefKeyEx.result=" + _getFaxSendMessagesByRefKeyEx__return);


        }
        {
        System.out.println("Invoking sendFaxFromFTP...");
        java.lang.String _sendFaxFromFTP_certkey = "";
        java.lang.String _sendFaxFromFTP_corpNum = "";
        java.lang.String _sendFaxFromFTP_senderID = "";
        java.lang.String _sendFaxFromFTP_fileName = "";
        java.lang.String _sendFaxFromFTP_fromNumber = "";
        java.lang.String _sendFaxFromFTP_toNumber = "";
        java.lang.String _sendFaxFromFTP_receiveCorp = "";
        java.lang.String _sendFaxFromFTP_receiveName = "";
        java.lang.String _sendFaxFromFTP_sendDT = "";
        java.lang.String _sendFaxFromFTP_refKey = "";
        java.lang.String _sendFaxFromFTP__return = port.sendFaxFromFTP(_sendFaxFromFTP_certkey, _sendFaxFromFTP_corpNum, _sendFaxFromFTP_senderID, _sendFaxFromFTP_fileName, _sendFaxFromFTP_fromNumber, _sendFaxFromFTP_toNumber, _sendFaxFromFTP_receiveCorp, _sendFaxFromFTP_receiveName, _sendFaxFromFTP_sendDT, _sendFaxFromFTP_refKey);
        System.out.println("sendFaxFromFTP.result=" + _sendFaxFromFTP__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking getFaxMessageEx...");
        java.lang.String _getFaxMessageEx_certkey = "";
        java.lang.String _getFaxMessageEx_corpNum = "";
        java.lang.String _getFaxMessageEx_sendKey = "";
        com.baroservice.ws.FaxMessageEx _getFaxMessageEx__return = port.getFaxMessageEx(_getFaxMessageEx_certkey, _getFaxMessageEx_corpNum, _getFaxMessageEx_sendKey);
        System.out.println("getFaxMessageEx.result=" + _getFaxMessageEx__return);


        }
        {
        System.out.println("Invoking getFaxFileURL...");
        java.lang.String _getFaxFileURL_certkey = "";
        java.lang.String _getFaxFileURL_corpNum = "";
        java.lang.String _getFaxFileURL_sendKey = "";
        int _getFaxFileURL_fileType = 0;
        com.baroservice.ws.ArrayOfString _getFaxFileURL__return = port.getFaxFileURL(_getFaxFileURL_certkey, _getFaxFileURL_corpNum, _getFaxFileURL_sendKey, _getFaxFileURL_fileType);
        System.out.println("getFaxFileURL.result=" + _getFaxFileURL__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking reSendFaxEx...");
        java.lang.String _reSendFaxEx_certkey = "";
        java.lang.String _reSendFaxEx_corpNum = "";
        java.lang.String _reSendFaxEx_senderID = "";
        java.lang.String _reSendFaxEx_sendKey = "";
        java.lang.String _reSendFaxEx_refKey = "";
        java.lang.String _reSendFaxEx_toNumber = "";
        java.lang.String _reSendFaxEx__return = port.reSendFaxEx(_reSendFaxEx_certkey, _reSendFaxEx_corpNum, _reSendFaxEx_senderID, _reSendFaxEx_sendKey, _reSendFaxEx_refKey, _reSendFaxEx_toNumber);
        System.out.println("reSendFaxEx.result=" + _reSendFaxEx__return);


        }
        {
        System.out.println("Invoking getFaxSendMessagesByPaging...");
        java.lang.String _getFaxSendMessagesByPaging_certkey = "";
        java.lang.String _getFaxSendMessagesByPaging_corpNum = "";
        java.lang.String _getFaxSendMessagesByPaging_fromDate = "";
        java.lang.String _getFaxSendMessagesByPaging_toDate = "";
        int _getFaxSendMessagesByPaging_countPerPage = 0;
        int _getFaxSendMessagesByPaging_currentPage = 0;
        com.baroservice.ws.PagedFaxMessages _getFaxSendMessagesByPaging__return = port.getFaxSendMessagesByPaging(_getFaxSendMessagesByPaging_certkey, _getFaxSendMessagesByPaging_corpNum, _getFaxSendMessagesByPaging_fromDate, _getFaxSendMessagesByPaging_toDate, _getFaxSendMessagesByPaging_countPerPage, _getFaxSendMessagesByPaging_currentPage);
        System.out.println("getFaxSendMessagesByPaging.result=" + _getFaxSendMessagesByPaging__return);


        }
        {
        System.out.println("Invoking getFaxSendMessages...");
        java.lang.String _getFaxSendMessages_certkey = "";
        java.lang.String _getFaxSendMessages_corpNum = "";
        com.baroservice.ws.ArrayOfString _getFaxSendMessages_sendKeyList = new com.baroservice.ws.ArrayOfString();
        com.baroservice.ws.ArrayOfFaxMessage _getFaxSendMessages__return = port.getFaxSendMessages(_getFaxSendMessages_certkey, _getFaxSendMessages_corpNum, _getFaxSendMessages_sendKeyList);
        System.out.println("getFaxSendMessages.result=" + _getFaxSendMessages__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
