package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 FAX 발송서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:40.745+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_FAX",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/fax.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceFAX extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_FAX");
    public final static QName BaroServiceFAXSoap12 = new QName("http://ws.baroservice.com/", "BaroService_FAXSoap12");
    public final static QName BaroServiceFAXSoap = new QName("http://ws.baroservice.com/", "BaroService_FAXSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/fax.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceFAX.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/fax.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceFAX(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceFAX(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceFAX() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceFAX(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceFAX(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceFAX(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceFAXSoap
     */
    @WebEndpoint(name = "BaroService_FAXSoap12")
    public BaroServiceFAXSoap getBaroServiceFAXSoap12() {
        return super.getPort(BaroServiceFAXSoap12, BaroServiceFAXSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceFAXSoap
     */
    @WebEndpoint(name = "BaroService_FAXSoap12")
    public BaroServiceFAXSoap getBaroServiceFAXSoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceFAXSoap12, BaroServiceFAXSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceFAXSoap
     */
    @WebEndpoint(name = "BaroService_FAXSoap")
    public BaroServiceFAXSoap getBaroServiceFAXSoap() {
        return super.getPort(BaroServiceFAXSoap, BaroServiceFAXSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceFAXSoap
     */
    @WebEndpoint(name = "BaroService_FAXSoap")
    public BaroServiceFAXSoap getBaroServiceFAXSoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceFAXSoap, BaroServiceFAXSoap.class, features);
    }

}
