package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 휴폐업조회 서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T12:00:13.456+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_CORPSTATE",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/corpstate.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceCORPSTATE extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_CORPSTATE");
    public final static QName BaroServiceCORPSTATESoap12 = new QName("http://ws.baroservice.com/", "BaroService_CORPSTATESoap12");
    public final static QName BaroServiceCORPSTATESoap = new QName("http://ws.baroservice.com/", "BaroService_CORPSTATESoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/corpstate.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceCORPSTATE.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/corpstate.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceCORPSTATE(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceCORPSTATE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceCORPSTATE() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceCORPSTATE(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceCORPSTATE(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceCORPSTATE(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceCORPSTATESoap
     */
    @WebEndpoint(name = "BaroService_CORPSTATESoap12")
    public BaroServiceCORPSTATESoap getBaroServiceCORPSTATESoap12() {
        return super.getPort(BaroServiceCORPSTATESoap12, BaroServiceCORPSTATESoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceCORPSTATESoap
     */
    @WebEndpoint(name = "BaroService_CORPSTATESoap12")
    public BaroServiceCORPSTATESoap getBaroServiceCORPSTATESoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceCORPSTATESoap12, BaroServiceCORPSTATESoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceCORPSTATESoap
     */
    @WebEndpoint(name = "BaroService_CORPSTATESoap")
    public BaroServiceCORPSTATESoap getBaroServiceCORPSTATESoap() {
        return super.getPort(BaroServiceCORPSTATESoap, BaroServiceCORPSTATESoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceCORPSTATESoap
     */
    @WebEndpoint(name = "BaroService_CORPSTATESoap")
    public BaroServiceCORPSTATESoap getBaroServiceCORPSTATESoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceCORPSTATESoap, BaroServiceCORPSTATESoap.class, features);
    }

}
