package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 세금계산서 연동서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:58:58.143+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_TI",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/ti.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceTI extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_TI");
    public final static QName BaroServiceTISoap = new QName("http://ws.baroservice.com/", "BaroService_TISoap");
    public final static QName BaroServiceTISoap12 = new QName("http://ws.baroservice.com/", "BaroService_TISoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/ti.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceTI.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/ti.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceTI(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceTI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceTI() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceTI(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceTI(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceTI(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceTISoap
     */
    @WebEndpoint(name = "BaroService_TISoap")
    public BaroServiceTISoap getBaroServiceTISoap() {
        return super.getPort(BaroServiceTISoap, BaroServiceTISoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceTISoap
     */
    @WebEndpoint(name = "BaroService_TISoap")
    public BaroServiceTISoap getBaroServiceTISoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceTISoap, BaroServiceTISoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceTISoap
     */
    @WebEndpoint(name = "BaroService_TISoap12")
    public BaroServiceTISoap getBaroServiceTISoap12() {
        return super.getPort(BaroServiceTISoap12, BaroServiceTISoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceTISoap
     */
    @WebEndpoint(name = "BaroService_TISoap12")
    public BaroServiceTISoap getBaroServiceTISoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceTISoap12, BaroServiceTISoap.class, features);
    }

}
