package com.baroservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:40.731+09:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://ws.baroservice.com/", name = "BaroService_FAXSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BaroServiceFAXSoap {

    /**
     * 회원사 관리자 변경
     */
    @WebMethod(operationName = "ChangeCorpManager", action = "http://ws.baroservice.com/ChangeCorpManager")
    @RequestWrapper(localName = "ChangeCorpManager", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ChangeCorpManager")
    @ResponseWrapper(localName = "ChangeCorpManagerResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ChangeCorpManagerResponse")
    @WebResult(name = "ChangeCorpManagerResult", targetNamespace = "http://ws.baroservice.com/")
    public int changeCorpManager(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "newManagerID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String newManagerID
    );

    /**
     * 회원사 가입여부 확인
     */
    @WebMethod(operationName = "CheckCorpIsMember", action = "http://ws.baroservice.com/CheckCorpIsMember")
    @RequestWrapper(localName = "CheckCorpIsMember", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCorpIsMember")
    @ResponseWrapper(localName = "CheckCorpIsMemberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCorpIsMemberResponse")
    @WebResult(name = "CheckCorpIsMemberResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkCorpIsMember(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String checkCorpNum
    );

    /**
     * 회원사 사용자 추가
     */
    @WebMethod(operationName = "AddUserToCorp", action = "http://ws.baroservice.com/AddUserToCorp")
    @RequestWrapper(localName = "AddUserToCorp", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.AddUserToCorp")
    @ResponseWrapper(localName = "AddUserToCorpResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.AddUserToCorpResponse")
    @WebResult(name = "AddUserToCorpResult", targetNamespace = "http://ws.baroservice.com/")
    public int addUserToCorp(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email
    );

    /**
     * FAX 재전송
     */
    @WebMethod(operationName = "ReSendFax", action = "http://ws.baroservice.com/ReSendFax")
    @RequestWrapper(localName = "ReSendFax", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ReSendFax")
    @ResponseWrapper(localName = "ReSendFaxResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ReSendFaxResponse")
    @WebResult(name = "ReSendFaxResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String reSendFax(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey
    );

    /**
     * 회원사 사용자 수정
     */
    @WebMethod(operationName = "UpdateUserInfo", action = "http://ws.baroservice.com/UpdateUserInfo")
    @RequestWrapper(localName = "UpdateUserInfo", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserInfo")
    @ResponseWrapper(localName = "UpdateUserInfoResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserInfoResponse")
    @WebResult(name = "UpdateUserInfoResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateUserInfo(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade
    );

    /**
     * FAX 전송 내역 조회 팝업
     */
    @WebMethod(operationName = "GetFaxHistoryURL", action = "http://ws.baroservice.com/GetFaxHistoryURL")
    @RequestWrapper(localName = "GetFaxHistoryURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxHistoryURL")
    @ResponseWrapper(localName = "GetFaxHistoryURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxHistoryURLResponse")
    @WebResult(name = "GetFaxHistoryURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getFaxHistoryURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 예약 전송 팩스 취소
     */
    @WebMethod(operationName = "CancelReservedFaxMessage", action = "http://ws.baroservice.com/CancelReservedFaxMessage")
    @RequestWrapper(localName = "CancelReservedFaxMessage", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CancelReservedFaxMessage")
    @ResponseWrapper(localName = "CancelReservedFaxMessageResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CancelReservedFaxMessageResponse")
    @WebResult(name = "CancelReservedFaxMessageResult", targetNamespace = "http://ws.baroservice.com/")
    public int cancelReservedFaxMessage(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey
    );

    /**
     * FAX 전송 (다량파일) [FTP 업로드가 선행되어야 합니다.]
     */
    @WebMethod(operationName = "SendFaxFromFTPEx", action = "http://ws.baroservice.com/SendFaxFromFTPEx")
    @RequestWrapper(localName = "SendFaxFromFTPEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxFromFTPEx")
    @ResponseWrapper(localName = "SendFaxFromFTPExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxFromFTPExResponse")
    @WebResult(name = "SendFaxFromFTPExResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String sendFaxFromFTPEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "FileCount", targetNamespace = "http://ws.baroservice.com/")
        int fileCount,
        @WebParam(name = "FileNames", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfString fileNames,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber,
        @WebParam(name = "ToNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String toNumber,
        @WebParam(name = "ReceiveCorp", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String receiveCorp,
        @WebParam(name = "ReceiveName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String receiveName,
        @WebParam(name = "SendDT", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendDT,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey
    );

    /**
     * FAX 전송 메시지 확인
     */
    @WebMethod(operationName = "GetFaxMessage", action = "http://ws.baroservice.com/GetFaxMessage")
    @RequestWrapper(localName = "GetFaxMessage", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxMessage")
    @ResponseWrapper(localName = "GetFaxMessageResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxMessageResponse")
    @WebResult(name = "GetFaxMessageResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.FaxMessage getFaxMessage(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey
    );

    /**
     * 바로빌 메인화면 URL 반환
     */
    @WebMethod(operationName = "GetLoginURL", action = "http://ws.baroservice.com/GetLoginURL")
    @RequestWrapper(localName = "GetLoginURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetLoginURL")
    @ResponseWrapper(localName = "GetLoginURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetLoginURLResponse")
    @WebResult(name = "GetLoginURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getLoginURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 연동참조번호 관련 FAX 메시지 확인
     */
    @WebMethod(operationName = "GetFaxSendMessagesByRefKey", action = "http://ws.baroservice.com/GetFaxSendMessagesByRefKey")
    @RequestWrapper(localName = "GetFaxSendMessagesByRefKey", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByRefKey")
    @ResponseWrapper(localName = "GetFaxSendMessagesByRefKeyResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByRefKeyResponse")
    @WebResult(name = "GetFaxSendMessagesByRefKeyResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfFaxMessage getFaxSendMessagesByRefKey(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey
    );

    /**
     * 등록한 공인인증서 등록일시 확인
     */
    @WebMethod(operationName = "GetCertificateRegistDate", action = "http://ws.baroservice.com/GetCertificateRegistDate")
    @RequestWrapper(localName = "GetCertificateRegistDate", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistDate")
    @ResponseWrapper(localName = "GetCertificateRegistDateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistDateResponse")
    @WebResult(name = "GetCertificateRegistDateResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateRegistDate(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 문자 발신번호 등록여부 확인
     */
    @WebMethod(operationName = "CheckSMSFromNumber", action = "http://ws.baroservice.com/CheckSMSFromNumber")
    @RequestWrapper(localName = "CheckSMSFromNumber", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckSMSFromNumber")
    @ResponseWrapper(localName = "CheckSMSFromNumberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckSMSFromNumberResponse")
    @WebResult(name = "CheckSMSFromNumberResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkSMSFromNumber(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber
    );

    /**
     * 문자 발신번호 추가
     */
    @WebMethod(operationName = "RegistSMSFromNumber", action = "http://ws.baroservice.com/RegistSMSFromNumber")
    @RequestWrapper(localName = "RegistSMSFromNumber", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistSMSFromNumber")
    @ResponseWrapper(localName = "RegistSMSFromNumberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistSMSFromNumberResponse")
    @WebResult(name = "RegistSMSFromNumberResult", targetNamespace = "http://ws.baroservice.com/")
    public int registSMSFromNumber(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber
    );

    /**
     * 과금가능 여부 확인
     */
    @WebMethod(operationName = "CheckChargeable", action = "http://ws.baroservice.com/CheckChargeable")
    @RequestWrapper(localName = "CheckChargeable", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckChargeable")
    @ResponseWrapper(localName = "CheckChargeableResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckChargeableResponse")
    @WebResult(name = "CheckChargeableResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkChargeable(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CType", targetNamespace = "http://ws.baroservice.com/")
        int cType,
        @WebParam(name = "DocType", targetNamespace = "http://ws.baroservice.com/")
        int docType
    );

    /**
     * Ping
     */
    @WebMethod(operationName = "Ping", action = "http://ws.baroservice.com/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.PingResponse")
    public void ping();

    /**
     * 회원사 충전잔액 확인
     */
    @WebMethod(operationName = "GetBalanceCostAmount", action = "http://ws.baroservice.com/GetBalanceCostAmount")
    @RequestWrapper(localName = "GetBalanceCostAmount", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmount")
    @ResponseWrapper(localName = "GetBalanceCostAmountResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountResponse")
    @WebResult(name = "GetBalanceCostAmountResult", targetNamespace = "http://ws.baroservice.com/")
    public long getBalanceCostAmount(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 바로빌 링크 연결 URL확인
     */
    @WebMethod(operationName = "GetBaroBillURL", action = "http://ws.baroservice.com/GetBaroBillURL")
    @RequestWrapper(localName = "GetBaroBillURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBaroBillURL")
    @ResponseWrapper(localName = "GetBaroBillURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBaroBillURLResponse")
    @WebResult(name = "GetBaroBillURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getBaroBillURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "TOGO", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String togo
    );

    /**
     * 오류코드의 상세내용 반환
     */
    @WebMethod(operationName = "GetErrString", action = "http://ws.baroservice.com/GetErrString")
    @RequestWrapper(localName = "GetErrString", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetErrString")
    @ResponseWrapper(localName = "GetErrStringResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetErrStringResponse")
    @WebResult(name = "GetErrStringResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getErrString(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "ErrCode", targetNamespace = "http://ws.baroservice.com/")
        int errCode
    );

    /**
     * 등록한 공인인증서 상태 확인
     */
    @WebMethod(operationName = "CheckCERTIsValid", action = "http://ws.baroservice.com/CheckCERTIsValid")
    @RequestWrapper(localName = "CheckCERTIsValid", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCERTIsValid")
    @ResponseWrapper(localName = "CheckCERTIsValidResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCERTIsValidResponse")
    @WebResult(name = "CheckCERTIsValidResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkCERTIsValid(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * FAX 전송 메시지 대량 확인[100건] (팩스파일 다운로드 URL 추가)
     */
    @WebMethod(operationName = "GetFaxSendMessagesEx", action = "http://ws.baroservice.com/GetFaxSendMessagesEx")
    @RequestWrapper(localName = "GetFaxSendMessagesEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesEx")
    @ResponseWrapper(localName = "GetFaxSendMessagesExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesExResponse")
    @WebResult(name = "GetFaxSendMessagesExResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfFaxMessageEx getFaxSendMessagesEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKeyList", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfString sendKeyList
    );

    /**
     * 회원사 담당자 목록확인
     */
    @WebMethod(operationName = "GetCorpMemberContacts", action = "http://ws.baroservice.com/GetCorpMemberContacts")
    @RequestWrapper(localName = "GetCorpMemberContacts", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpMemberContacts")
    @ResponseWrapper(localName = "GetCorpMemberContactsResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpMemberContactsResponse")
    @WebResult(name = "GetCorpMemberContactsResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfContact getCorpMemberContacts(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String checkCorpNum
    );

    /**
     * 문자 발신번호 관리 URL 반환
     */
    @WebMethod(operationName = "GetSMSFromNumberURL", action = "http://ws.baroservice.com/GetSMSFromNumberURL")
    @RequestWrapper(localName = "GetSMSFromNumberURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetSMSFromNumberURL")
    @ResponseWrapper(localName = "GetSMSFromNumberURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetSMSFromNumberURLResponse")
    @WebResult(name = "GetSMSFromNumberURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getSMSFromNumberURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * FAX 대량전송 (단일파일) [FTP 업로드가 선행되어야 합니다.]
     */
    @WebMethod(operationName = "SendFaxesFromFTP", action = "http://ws.baroservice.com/SendFaxesFromFTP")
    @RequestWrapper(localName = "SendFaxesFromFTP", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxesFromFTP")
    @ResponseWrapper(localName = "SendFaxesFromFTPResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxesFromFTPResponse")
    @WebResult(name = "SendFaxesFromFTPResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfString sendFaxesFromFTP(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "FileName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fileName,
        @WebParam(name = "SendCount", targetNamespace = "http://ws.baroservice.com/")
        int sendCount,
        @WebParam(name = "Messages", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfFaxMessage messages,
        @WebParam(name = "SendDT", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendDT
    );

    /**
     * 등록한 공인인증서 만료일 확인
     */
    @WebMethod(operationName = "GetCertificateExpireDate", action = "http://ws.baroservice.com/GetCertificateExpireDate")
    @RequestWrapper(localName = "GetCertificateExpireDate", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateExpireDate")
    @ResponseWrapper(localName = "GetCertificateExpireDateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateExpireDateResponse")
    @WebResult(name = "GetCertificateExpireDateResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateExpireDate(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * FAX 대량전송 (다량파일) [FTP 업로드가 선행되어야 합니다.]
     */
    @WebMethod(operationName = "SendFaxesFromFTPEx", action = "http://ws.baroservice.com/SendFaxesFromFTPEx")
    @RequestWrapper(localName = "SendFaxesFromFTPEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxesFromFTPEx")
    @ResponseWrapper(localName = "SendFaxesFromFTPExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxesFromFTPExResponse")
    @WebResult(name = "SendFaxesFromFTPExResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfString sendFaxesFromFTPEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "FileCount", targetNamespace = "http://ws.baroservice.com/")
        int fileCount,
        @WebParam(name = "FileNames", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfString fileNames,
        @WebParam(name = "SendCount", targetNamespace = "http://ws.baroservice.com/")
        int sendCount,
        @WebParam(name = "Messages", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfFaxMessage messages,
        @WebParam(name = "SendDT", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendDT
    );

    /**
     * 회원사 사용자 비밀번호 변경
     */
    @WebMethod(operationName = "UpdateUserPWD", action = "http://ws.baroservice.com/UpdateUserPWD")
    @RequestWrapper(localName = "UpdateUserPWD", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserPWD")
    @ResponseWrapper(localName = "UpdateUserPWDResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserPWDResponse")
    @WebResult(name = "UpdateUserPWDResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateUserPWD(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "newPWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String newPWD
    );

    /**
     * 포인트 충전 URL 반환
     */
    @WebMethod(operationName = "GetCashChargeURL", action = "http://ws.baroservice.com/GetCashChargeURL")
    @RequestWrapper(localName = "GetCashChargeURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCashChargeURL")
    @ResponseWrapper(localName = "GetCashChargeURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCashChargeURLResponse")
    @WebResult(name = "GetCashChargeURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCashChargeURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 공인인증서 등록 URL 확인
     */
    @WebMethod(operationName = "GetCertificateRegistURL", action = "http://ws.baroservice.com/GetCertificateRegistURL")
    @RequestWrapper(localName = "GetCertificateRegistURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistURL")
    @ResponseWrapper(localName = "GetCertificateRegistURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistURLResponse")
    @WebResult(name = "GetCertificateRegistURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateRegistURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * FAX 전송 상태 확인
     */
    @WebMethod(operationName = "GetFaxSendState", action = "http://ws.baroservice.com/GetFaxSendState")
    @RequestWrapper(localName = "GetFaxSendState", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendState")
    @ResponseWrapper(localName = "GetFaxSendStateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendStateResponse")
    @WebResult(name = "GetFaxSendStateResult", targetNamespace = "http://ws.baroservice.com/")
    public int getFaxSendState(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey
    );

    /**
     * 연동참조번호 관련 FAX 메시지 확인 (팩스파일 다운로드 URL 추가)
     */
    @WebMethod(operationName = "GetFaxSendMessagesByRefKeyEx", action = "http://ws.baroservice.com/GetFaxSendMessagesByRefKeyEx")
    @RequestWrapper(localName = "GetFaxSendMessagesByRefKeyEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByRefKeyEx")
    @ResponseWrapper(localName = "GetFaxSendMessagesByRefKeyExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByRefKeyExResponse")
    @WebResult(name = "GetFaxSendMessagesByRefKeyExResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfFaxMessageEx getFaxSendMessagesByRefKeyEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey
    );

    /**
     * FAX 전송 (단일파일) [FTP 업로드가 선행되어야 합니다.]
     */
    @WebMethod(operationName = "SendFaxFromFTP", action = "http://ws.baroservice.com/SendFaxFromFTP")
    @RequestWrapper(localName = "SendFaxFromFTP", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxFromFTP")
    @ResponseWrapper(localName = "SendFaxFromFTPResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.SendFaxFromFTPResponse")
    @WebResult(name = "SendFaxFromFTPResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String sendFaxFromFTP(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "FileName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fileName,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber,
        @WebParam(name = "ToNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String toNumber,
        @WebParam(name = "ReceiveCorp", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String receiveCorp,
        @WebParam(name = "ReceiveName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String receiveName,
        @WebParam(name = "SendDT", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendDT,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey
    );

    /**
     * 회원사 수정
     */
    @WebMethod(operationName = "UpdateCorpInfo", action = "http://ws.baroservice.com/UpdateCorpInfo")
    @RequestWrapper(localName = "UpdateCorpInfo", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateCorpInfo")
    @ResponseWrapper(localName = "UpdateCorpInfoResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateCorpInfoResponse")
    @WebResult(name = "UpdateCorpInfoResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateCorpInfo(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CorpName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpName,
        @WebParam(name = "CEOName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String ceoName,
        @WebParam(name = "BizType", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizType,
        @WebParam(name = "BizClass", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizClass,
        @WebParam(name = "PostNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String postNum,
        @WebParam(name = "Addr1", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr1,
        @WebParam(name = "Addr2", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr2
    );

    /**
     * FAX 전송 메시지 확인 (팩스파일 다운로드 URL 추가)
     */
    @WebMethod(operationName = "GetFaxMessageEx", action = "http://ws.baroservice.com/GetFaxMessageEx")
    @RequestWrapper(localName = "GetFaxMessageEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxMessageEx")
    @ResponseWrapper(localName = "GetFaxMessageExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxMessageExResponse")
    @WebResult(name = "GetFaxMessageExResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.FaxMessageEx getFaxMessageEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey
    );

    /**
     * FAX 파일 다운로드 URL
     */
    @WebMethod(operationName = "GetFaxFileURL", action = "http://ws.baroservice.com/GetFaxFileURL")
    @RequestWrapper(localName = "GetFaxFileURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxFileURL")
    @ResponseWrapper(localName = "GetFaxFileURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxFileURLResponse")
    @WebResult(name = "GetFaxFileURLResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfString getFaxFileURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey,
        @WebParam(name = "FileType", targetNamespace = "http://ws.baroservice.com/")
        int fileType
    );

    /**
     * 회원사 가입
     */
    @WebMethod(operationName = "RegistCorp", action = "http://ws.baroservice.com/RegistCorp")
    @RequestWrapper(localName = "RegistCorp", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistCorp")
    @ResponseWrapper(localName = "RegistCorpResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistCorpResponse")
    @WebResult(name = "RegistCorpResult", targetNamespace = "http://ws.baroservice.com/")
    public int registCorp(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CorpName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpName,
        @WebParam(name = "CEOName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String ceoName,
        @WebParam(name = "BizType", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizType,
        @WebParam(name = "BizClass", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizClass,
        @WebParam(name = "PostNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String postNum,
        @WebParam(name = "Addr1", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr1,
        @WebParam(name = "Addr2", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr2,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email
    );

    /**
     * FAX 재전송
     */
    @WebMethod(operationName = "ReSendFaxEx", action = "http://ws.baroservice.com/ReSendFaxEx")
    @RequestWrapper(localName = "ReSendFaxEx", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ReSendFaxEx")
    @ResponseWrapper(localName = "ReSendFaxExResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ReSendFaxExResponse")
    @WebResult(name = "ReSendFaxExResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String reSendFaxEx(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SenderID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String senderID,
        @WebParam(name = "SendKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String sendKey,
        @WebParam(name = "RefKey", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String refKey,
        @WebParam(name = "ToNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String toNumber
    );

    /**
     * 페이징에 의한 관련 메시지 확인
     */
    @WebMethod(operationName = "GetFaxSendMessagesByPaging", action = "http://ws.baroservice.com/GetFaxSendMessagesByPaging")
    @RequestWrapper(localName = "GetFaxSendMessagesByPaging", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByPaging")
    @ResponseWrapper(localName = "GetFaxSendMessagesByPagingResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesByPagingResponse")
    @WebResult(name = "GetFaxSendMessagesByPagingResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.PagedFaxMessages getFaxSendMessagesByPaging(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "FromDate", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String toDate,
        @WebParam(name = "CountPerPage", targetNamespace = "http://ws.baroservice.com/")
        int countPerPage,
        @WebParam(name = "CurrentPage", targetNamespace = "http://ws.baroservice.com/")
        int currentPage
    );

    /**
     * FAX 전송 메시지 대량 확인[100건]
     */
    @WebMethod(operationName = "GetFaxSendMessages", action = "http://ws.baroservice.com/GetFaxSendMessages")
    @RequestWrapper(localName = "GetFaxSendMessages", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessages")
    @ResponseWrapper(localName = "GetFaxSendMessagesResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetFaxSendMessagesResponse")
    @WebResult(name = "GetFaxSendMessagesResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfFaxMessage getFaxSendMessages(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "SendKeyList", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfString sendKeyList
    );

    /**
     * 연동사 충전잔액 확인
     */
    @WebMethod(operationName = "GetBalanceCostAmountOfInterOP", action = "http://ws.baroservice.com/GetBalanceCostAmountOfInterOP")
    @RequestWrapper(localName = "GetBalanceCostAmountOfInterOP", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountOfInterOP")
    @ResponseWrapper(localName = "GetBalanceCostAmountOfInterOPResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountOfInterOPResponse")
    @WebResult(name = "GetBalanceCostAmountOfInterOPResult", targetNamespace = "http://ws.baroservice.com/")
    public long getBalanceCostAmountOfInterOP(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey
    );

    /**
     * 단가 확인
     */
    @WebMethod(operationName = "GetChargeUnitCost", action = "http://ws.baroservice.com/GetChargeUnitCost")
    @RequestWrapper(localName = "GetChargeUnitCost", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetChargeUnitCost")
    @ResponseWrapper(localName = "GetChargeUnitCostResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetChargeUnitCostResponse")
    @WebResult(name = "GetChargeUnitCostResult", targetNamespace = "http://ws.baroservice.com/")
    public int getChargeUnitCost(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ChargeCode", targetNamespace = "http://ws.baroservice.com/")
        int chargeCode
    );
}
