package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 계좌조회 서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T12:00:03.633+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_BANKACCOUNT",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/bankaccount.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceBANKACCOUNT extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_BANKACCOUNT");
    public final static QName BaroServiceBANKACCOUNTSoap12 = new QName("http://ws.baroservice.com/", "BaroService_BANKACCOUNTSoap12");
    public final static QName BaroServiceBANKACCOUNTSoap = new QName("http://ws.baroservice.com/", "BaroService_BANKACCOUNTSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/bankaccount.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceBANKACCOUNT.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/bankaccount.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceBANKACCOUNT(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceBANKACCOUNT(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceBANKACCOUNT() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceBANKACCOUNT(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceBANKACCOUNT(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceBANKACCOUNT(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceBANKACCOUNTSoap
     */
    @WebEndpoint(name = "BaroService_BANKACCOUNTSoap12")
    public BaroServiceBANKACCOUNTSoap getBaroServiceBANKACCOUNTSoap12() {
        return super.getPort(BaroServiceBANKACCOUNTSoap12, BaroServiceBANKACCOUNTSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceBANKACCOUNTSoap
     */
    @WebEndpoint(name = "BaroService_BANKACCOUNTSoap12")
    public BaroServiceBANKACCOUNTSoap getBaroServiceBANKACCOUNTSoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceBANKACCOUNTSoap12, BaroServiceBANKACCOUNTSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceBANKACCOUNTSoap
     */
    @WebEndpoint(name = "BaroService_BANKACCOUNTSoap")
    public BaroServiceBANKACCOUNTSoap getBaroServiceBANKACCOUNTSoap() {
        return super.getPort(BaroServiceBANKACCOUNTSoap, BaroServiceBANKACCOUNTSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceBANKACCOUNTSoap
     */
    @WebEndpoint(name = "BaroService_BANKACCOUNTSoap")
    public BaroServiceBANKACCOUNTSoap getBaroServiceBANKACCOUNTSoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceBANKACCOUNTSoap, BaroServiceBANKACCOUNTSoap.class, features);
    }

}
