
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:18.293+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceCASHBILLSoap_BaroServiceCASHBILLSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_CASHBILL");

    private BaroServiceCASHBILLSoap_BaroServiceCASHBILLSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceCASHBILL.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceCASHBILL ss = new BaroServiceCASHBILL(wsdlURL, SERVICE_NAME);
        BaroServiceCASHBILLSoap port = ss.getBaroServiceCASHBILLSoap();

        {
        System.out.println("Invoking deleteCashBill...");
        java.lang.String _deleteCashBill_certkey = "";
        java.lang.String _deleteCashBill_corpNum = "";
        java.lang.String _deleteCashBill_userID = "";
        java.lang.String _deleteCashBill_mgtKey = "";
        int _deleteCashBill__return = port.deleteCashBill(_deleteCashBill_certkey, _deleteCashBill_corpNum, _deleteCashBill_userID, _deleteCashBill_mgtKey);
        System.out.println("deleteCashBill.result=" + _deleteCashBill__return);


        }
        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking getCashBillStates...");
        java.lang.String _getCashBillStates_certkey = "";
        java.lang.String _getCashBillStates_corpNum = "";
        java.lang.String _getCashBillStates_userID = "";
        com.baroservice.ws.ArrayOfString _getCashBillStates_mgtKeyList = new com.baroservice.ws.ArrayOfString();
        com.baroservice.ws.ArrayOfCashBillState _getCashBillStates__return = port.getCashBillStates(_getCashBillStates_certkey, _getCashBillStates_corpNum, _getCashBillStates_userID, _getCashBillStates_mgtKeyList);
        System.out.println("getCashBillStates.result=" + _getCashBillStates__return);


        }
        {
        System.out.println("Invoking removeDocLinkage...");
        java.lang.String _removeDocLinkage_certkey = "";
        java.lang.String _removeDocLinkage_corpNum = "";
        int _removeDocLinkage_fromDocType = 0;
        java.lang.String _removeDocLinkage_fromMgtKey = "";
        int _removeDocLinkage_toDocType = 0;
        java.lang.String _removeDocLinkage_toMgtKey = "";
        int _removeDocLinkage__return = port.removeDocLinkage(_removeDocLinkage_certkey, _removeDocLinkage_corpNum, _removeDocLinkage_fromDocType, _removeDocLinkage_fromMgtKey, _removeDocLinkage_toDocType, _removeDocLinkage_toMgtKey);
        System.out.println("removeDocLinkage.result=" + _removeDocLinkage__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getCashBillPurchaseList...");
        java.lang.String _getCashBillPurchaseList_certkey = "";
        java.lang.String _getCashBillPurchaseList_corpNum = "";
        java.lang.String _getCashBillPurchaseList_userID = "";
        java.lang.String _getCashBillPurchaseList_baseDate = "";
        int _getCashBillPurchaseList_countPerPage = 0;
        int _getCashBillPurchaseList_currentPage = 0;
        com.baroservice.ws.PagedCashBill _getCashBillPurchaseList__return = port.getCashBillPurchaseList(_getCashBillPurchaseList_certkey, _getCashBillPurchaseList_corpNum, _getCashBillPurchaseList_userID, _getCashBillPurchaseList_baseDate, _getCashBillPurchaseList_countPerPage, _getCashBillPurchaseList_currentPage);
        System.out.println("getCashBillPurchaseList.result=" + _getCashBillPurchaseList__return);


        }
        {
        System.out.println("Invoking getCashBill...");
        java.lang.String _getCashBill_certkey = "";
        java.lang.String _getCashBill_corpNum = "";
        java.lang.String _getCashBill_userID = "";
        java.lang.String _getCashBill_mgtKey = "";
        com.baroservice.ws.CashBill _getCashBill__return = port.getCashBill(_getCashBill_certkey, _getCashBill_corpNum, _getCashBill_userID, _getCashBill_mgtKey);
        System.out.println("getCashBill.result=" + _getCashBill__return);


        }
        {
        System.out.println("Invoking getCashBillPurchaseListByID...");
        java.lang.String _getCashBillPurchaseListByID_certkey = "";
        java.lang.String _getCashBillPurchaseListByID_corpNum = "";
        java.lang.String _getCashBillPurchaseListByID_userID = "";
        java.lang.String _getCashBillPurchaseListByID_baseDate = "";
        int _getCashBillPurchaseListByID_countPerPage = 0;
        int _getCashBillPurchaseListByID_currentPage = 0;
        com.baroservice.ws.PagedCashBill _getCashBillPurchaseListByID__return = port.getCashBillPurchaseListByID(_getCashBillPurchaseListByID_certkey, _getCashBillPurchaseListByID_corpNum, _getCashBillPurchaseListByID_userID, _getCashBillPurchaseListByID_baseDate, _getCashBillPurchaseListByID_countPerPage, _getCashBillPurchaseListByID_currentPage);
        System.out.println("getCashBillPurchaseListByID.result=" + _getCashBillPurchaseListByID__return);


        }
        {
        System.out.println("Invoking cancelCashBill...");
        java.lang.String _cancelCashBill_certkey = "";
        java.lang.String _cancelCashBill_corpNum = "";
        java.lang.String _cancelCashBill_userID = "";
        java.lang.String _cancelCashBill_mgtKey = "";
        java.lang.String _cancelCashBill_cancelType = "";
        boolean _cancelCashBill_smsSendYN = false;
        java.lang.String _cancelCashBill_mailTitle = "";
        int _cancelCashBill__return = port.cancelCashBill(_cancelCashBill_certkey, _cancelCashBill_corpNum, _cancelCashBill_userID, _cancelCashBill_mgtKey, _cancelCashBill_cancelType, _cancelCashBill_smsSendYN, _cancelCashBill_mailTitle);
        System.out.println("cancelCashBill.result=" + _cancelCashBill__return);


        }
        {
        System.out.println("Invoking getMonthlyCashBillPurchaseList...");
        java.lang.String _getMonthlyCashBillPurchaseList_certkey = "";
        java.lang.String _getMonthlyCashBillPurchaseList_corpNum = "";
        java.lang.String _getMonthlyCashBillPurchaseList_userID = "";
        java.lang.String _getMonthlyCashBillPurchaseList_baseMonth = "";
        int _getMonthlyCashBillPurchaseList_countPerPage = 0;
        int _getMonthlyCashBillPurchaseList_currentPage = 0;
        int _getMonthlyCashBillPurchaseList_orderDirection = 0;
        com.baroservice.ws.PagedCashBill _getMonthlyCashBillPurchaseList__return = port.getMonthlyCashBillPurchaseList(_getMonthlyCashBillPurchaseList_certkey, _getMonthlyCashBillPurchaseList_corpNum, _getMonthlyCashBillPurchaseList_userID, _getMonthlyCashBillPurchaseList_baseMonth, _getMonthlyCashBillPurchaseList_countPerPage, _getMonthlyCashBillPurchaseList_currentPage, _getMonthlyCashBillPurchaseList_orderDirection);
        System.out.println("getMonthlyCashBillPurchaseList.result=" + _getMonthlyCashBillPurchaseList__return);


        }
        {
        System.out.println("Invoking getCashBillScrapRequestURL...");
        java.lang.String _getCashBillScrapRequestURL_certkey = "";
        java.lang.String _getCashBillScrapRequestURL_corpNum = "";
        java.lang.String _getCashBillScrapRequestURL_userID = "";
        java.lang.String _getCashBillScrapRequestURL_pwd = "";
        java.lang.String _getCashBillScrapRequestURL__return = port.getCashBillScrapRequestURL(_getCashBillScrapRequestURL_certkey, _getCashBillScrapRequestURL_corpNum, _getCashBillScrapRequestURL_userID, _getCashBillScrapRequestURL_pwd);
        System.out.println("getCashBillScrapRequestURL.result=" + _getCashBillScrapRequestURL__return);


        }
        {
        System.out.println("Invoking checkIsValidCashBill...");
        java.lang.String _checkIsValidCashBill_certkey = "";
        java.lang.String _checkIsValidCashBill_corpNum = "";
        com.baroservice.ws.CashBill _checkIsValidCashBill_invoice = new com.baroservice.ws.CashBill();
        int _checkIsValidCashBill__return = port.checkIsValidCashBill(_checkIsValidCashBill_certkey, _checkIsValidCashBill_corpNum, _checkIsValidCashBill_invoice);
        System.out.println("checkIsValidCashBill.result=" + _checkIsValidCashBill__return);


        }
        {
        System.out.println("Invoking getBusinessLicenseRegistURL...");
        java.lang.String _getBusinessLicenseRegistURL_certkey = "";
        java.lang.String _getBusinessLicenseRegistURL_corpNum = "";
        java.lang.String _getBusinessLicenseRegistURL_userID = "";
        java.lang.String _getBusinessLicenseRegistURL_pwd = "";
        java.lang.String _getBusinessLicenseRegistURL__return = port.getBusinessLicenseRegistURL(_getBusinessLicenseRegistURL_certkey, _getBusinessLicenseRegistURL_corpNum, _getBusinessLicenseRegistURL_userID, _getBusinessLicenseRegistURL_pwd);
        System.out.println("getBusinessLicenseRegistURL.result=" + _getBusinessLicenseRegistURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking issueCashBill...");
        java.lang.String _issueCashBill_certkey = "";
        java.lang.String _issueCashBill_corpNum = "";
        java.lang.String _issueCashBill_userID = "";
        java.lang.String _issueCashBill_mgtKey = "";
        boolean _issueCashBill_smsSendYN = false;
        java.lang.String _issueCashBill_mailTitle = "";
        int _issueCashBill__return = port.issueCashBill(_issueCashBill_certkey, _issueCashBill_corpNum, _issueCashBill_userID, _issueCashBill_mgtKey, _issueCashBill_smsSendYN, _issueCashBill_mailTitle);
        System.out.println("issueCashBill.result=" + _issueCashBill__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking getCashBillLog...");
        java.lang.String _getCashBillLog_certkey = "";
        java.lang.String _getCashBillLog_corpNum = "";
        java.lang.String _getCashBillLog_userID = "";
        java.lang.String _getCashBillLog_mgtKey = "";
        com.baroservice.ws.ArrayOfCashBillLog _getCashBillLog__return = port.getCashBillLog(_getCashBillLog_certkey, _getCashBillLog_corpNum, _getCashBillLog_userID, _getCashBillLog_mgtKey);
        System.out.println("getCashBillLog.result=" + _getCashBillLog__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getMonthlyCashBillSalesList...");
        java.lang.String _getMonthlyCashBillSalesList_certkey = "";
        java.lang.String _getMonthlyCashBillSalesList_corpNum = "";
        java.lang.String _getMonthlyCashBillSalesList_userID = "";
        java.lang.String _getMonthlyCashBillSalesList_baseMonth = "";
        int _getMonthlyCashBillSalesList_countPerPage = 0;
        int _getMonthlyCashBillSalesList_currentPage = 0;
        int _getMonthlyCashBillSalesList_orderDirection = 0;
        com.baroservice.ws.PagedCashBill _getMonthlyCashBillSalesList__return = port.getMonthlyCashBillSalesList(_getMonthlyCashBillSalesList_certkey, _getMonthlyCashBillSalesList_corpNum, _getMonthlyCashBillSalesList_userID, _getMonthlyCashBillSalesList_baseMonth, _getMonthlyCashBillSalesList_countPerPage, _getMonthlyCashBillSalesList_currentPage, _getMonthlyCashBillSalesList_orderDirection);
        System.out.println("getMonthlyCashBillSalesList.result=" + _getMonthlyCashBillSalesList__return);


        }
        {
        System.out.println("Invoking getBankBookRegistURL...");
        java.lang.String _getBankBookRegistURL_certkey = "";
        java.lang.String _getBankBookRegistURL_corpNum = "";
        java.lang.String _getBankBookRegistURL_userID = "";
        java.lang.String _getBankBookRegistURL_pwd = "";
        java.lang.String _getBankBookRegistURL__return = port.getBankBookRegistURL(_getBankBookRegistURL_certkey, _getBankBookRegistURL_corpNum, _getBankBookRegistURL_userID, _getBankBookRegistURL_pwd);
        System.out.println("getBankBookRegistURL.result=" + _getBankBookRegistURL__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking getCashBillState...");
        java.lang.String _getCashBillState_certkey = "";
        java.lang.String _getCashBillState_corpNum = "";
        java.lang.String _getCashBillState_userID = "";
        java.lang.String _getCashBillState_mgtKey = "";
        com.baroservice.ws.CashBillState _getCashBillState__return = port.getCashBillState(_getCashBillState_certkey, _getCashBillState_corpNum, _getCashBillState_userID, _getCashBillState_mgtKey);
        System.out.println("getCashBillState.result=" + _getCashBillState__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking getJicInRegistURL...");
        java.lang.String _getJicInRegistURL_certkey = "";
        java.lang.String _getJicInRegistURL_corpNum = "";
        java.lang.String _getJicInRegistURL_userID = "";
        java.lang.String _getJicInRegistURL_pwd = "";
        java.lang.String _getJicInRegistURL__return = port.getJicInRegistURL(_getJicInRegistURL_certkey, _getJicInRegistURL_corpNum, _getJicInRegistURL_userID, _getJicInRegistURL_pwd);
        System.out.println("getJicInRegistURL.result=" + _getJicInRegistURL__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking cancelCashBillPartial...");
        java.lang.String _cancelCashBillPartial_certkey = "";
        java.lang.String _cancelCashBillPartial_corpNum = "";
        java.lang.String _cancelCashBillPartial_userID = "";
        java.lang.String _cancelCashBillPartial_mgtKey = "";
        java.lang.String _cancelCashBillPartial_cancelType = "";
        java.lang.String _cancelCashBillPartial_cancelAmount = "";
        java.lang.String _cancelCashBillPartial_cancelTax = "";
        java.lang.String _cancelCashBillPartial_cancelServiceCharge = "";
        boolean _cancelCashBillPartial_smsSendYN = false;
        java.lang.String _cancelCashBillPartial_mailTitle = "";
        int _cancelCashBillPartial__return = port.cancelCashBillPartial(_cancelCashBillPartial_certkey, _cancelCashBillPartial_corpNum, _cancelCashBillPartial_userID, _cancelCashBillPartial_mgtKey, _cancelCashBillPartial_cancelType, _cancelCashBillPartial_cancelAmount, _cancelCashBillPartial_cancelTax, _cancelCashBillPartial_cancelServiceCharge, _cancelCashBillPartial_smsSendYN, _cancelCashBillPartial_mailTitle);
        System.out.println("cancelCashBillPartial.result=" + _cancelCashBillPartial__return);


        }
        {
        System.out.println("Invoking getCashBillsPrintURL...");
        java.lang.String _getCashBillsPrintURL_certkey = "";
        java.lang.String _getCashBillsPrintURL_corpNum = "";
        java.lang.String _getCashBillsPrintURL_userID = "";
        java.lang.String _getCashBillsPrintURL_pwd = "";
        com.baroservice.ws.ArrayOfString _getCashBillsPrintURL_mgtKeyList = new com.baroservice.ws.ArrayOfString();
        java.lang.String _getCashBillsPrintURL__return = port.getCashBillsPrintURL(_getCashBillsPrintURL_certkey, _getCashBillsPrintURL_corpNum, _getCashBillsPrintURL_userID, _getCashBillsPrintURL_pwd, _getCashBillsPrintURL_mgtKeyList);
        System.out.println("getCashBillsPrintURL.result=" + _getCashBillsPrintURL__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getLinkedDocs...");
        java.lang.String _getLinkedDocs_certkey = "";
        java.lang.String _getLinkedDocs_corpNum = "";
        int _getLinkedDocs_docType = 0;
        java.lang.String _getLinkedDocs_mgtKey = "";
        com.baroservice.ws.ArrayOfLinkedDoc _getLinkedDocs__return = port.getLinkedDocs(_getLinkedDocs_certkey, _getLinkedDocs_corpNum, _getLinkedDocs_docType, _getLinkedDocs_mgtKey);
        System.out.println("getLinkedDocs.result=" + _getLinkedDocs__return);


        }
        {
        System.out.println("Invoking sendSMS...");
        java.lang.String _sendSMS_certkey = "";
        java.lang.String _sendSMS_corpNum = "";
        java.lang.String _sendSMS_userID = "";
        java.lang.String _sendSMS_mgtKey = "";
        java.lang.String _sendSMS_fromNumber = "";
        java.lang.String _sendSMS_toNumber = "";
        java.lang.String _sendSMS_contents = "";
        int _sendSMS__return = port.sendSMS(_sendSMS_certkey, _sendSMS_corpNum, _sendSMS_userID, _sendSMS_mgtKey, _sendSMS_fromNumber, _sendSMS_toNumber, _sendSMS_contents);
        System.out.println("sendSMS.result=" + _sendSMS__return);


        }
        {
        System.out.println("Invoking getCashBillMailURL...");
        java.lang.String _getCashBillMailURL_certkey = "";
        java.lang.String _getCashBillMailURL_corpNum = "";
        java.lang.String _getCashBillMailURL_userID = "";
        java.lang.String _getCashBillMailURL_mgtKey = "";
        java.lang.String _getCashBillMailURL__return = port.getCashBillMailURL(_getCashBillMailURL_certkey, _getCashBillMailURL_corpNum, _getCashBillMailURL_userID, _getCashBillMailURL_mgtKey);
        System.out.println("getCashBillMailURL.result=" + _getCashBillMailURL__return);


        }
        {
        System.out.println("Invoking registCashBill...");
        java.lang.String _registCashBill_certkey = "";
        java.lang.String _registCashBill_corpNum = "";
        java.lang.String _registCashBill_userID = "";
        com.baroservice.ws.CashBill _registCashBill_invoice = new com.baroservice.ws.CashBill();
        int _registCashBill__return = port.registCashBill(_registCashBill_certkey, _registCashBill_corpNum, _registCashBill_userID, _registCashBill_invoice);
        System.out.println("registCashBill.result=" + _registCashBill__return);


        }
        {
        System.out.println("Invoking getCashBillSalesList...");
        java.lang.String _getCashBillSalesList_certkey = "";
        java.lang.String _getCashBillSalesList_corpNum = "";
        java.lang.String _getCashBillSalesList_userID = "";
        java.lang.String _getCashBillSalesList_baseDate = "";
        int _getCashBillSalesList_countPerPage = 0;
        int _getCashBillSalesList_currentPage = 0;
        com.baroservice.ws.PagedCashBill _getCashBillSalesList__return = port.getCashBillSalesList(_getCashBillSalesList_certkey, _getCashBillSalesList_corpNum, _getCashBillSalesList_userID, _getCashBillSalesList_baseDate, _getCashBillSalesList_countPerPage, _getCashBillSalesList_currentPage);
        System.out.println("getCashBillSalesList.result=" + _getCashBillSalesList__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking checkMgtKeyIsExists...");
        java.lang.String _checkMgtKeyIsExists_certkey = "";
        java.lang.String _checkMgtKeyIsExists_corpNum = "";
        java.lang.String _checkMgtKeyIsExists_userID = "";
        java.lang.String _checkMgtKeyIsExists_mgtKey = "";
        int _checkMgtKeyIsExists__return = port.checkMgtKeyIsExists(_checkMgtKeyIsExists_certkey, _checkMgtKeyIsExists_corpNum, _checkMgtKeyIsExists_userID, _checkMgtKeyIsExists_mgtKey);
        System.out.println("checkMgtKeyIsExists.result=" + _checkMgtKeyIsExists__return);


        }
        {
        System.out.println("Invoking makeDocLinkage...");
        java.lang.String _makeDocLinkage_certkey = "";
        java.lang.String _makeDocLinkage_corpNum = "";
        int _makeDocLinkage_fromDocType = 0;
        java.lang.String _makeDocLinkage_fromMgtKey = "";
        int _makeDocLinkage_toDocType = 0;
        java.lang.String _makeDocLinkage_toMgtKey = "";
        int _makeDocLinkage__return = port.makeDocLinkage(_makeDocLinkage_certkey, _makeDocLinkage_corpNum, _makeDocLinkage_fromDocType, _makeDocLinkage_fromMgtKey, _makeDocLinkage_toDocType, _makeDocLinkage_toMgtKey);
        System.out.println("makeDocLinkage.result=" + _makeDocLinkage__return);


        }
        {
        System.out.println("Invoking sendEmail...");
        java.lang.String _sendEmail_certkey = "";
        java.lang.String _sendEmail_corpNum = "";
        java.lang.String _sendEmail_userID = "";
        java.lang.String _sendEmail_mgtKey = "";
        java.lang.String _sendEmail_toEmailAddress = "";
        int _sendEmail__return = port.sendEmail(_sendEmail_certkey, _sendEmail_corpNum, _sendEmail_userID, _sendEmail_mgtKey, _sendEmail_toEmailAddress);
        System.out.println("sendEmail.result=" + _sendEmail__return);


        }
        {
        System.out.println("Invoking cancelCashBillBeforeNTSSend...");
        java.lang.String _cancelCashBillBeforeNTSSend_certkey = "";
        java.lang.String _cancelCashBillBeforeNTSSend_corpNum = "";
        java.lang.String _cancelCashBillBeforeNTSSend_userID = "";
        java.lang.String _cancelCashBillBeforeNTSSend_mgtKey = "";
        int _cancelCashBillBeforeNTSSend__return = port.cancelCashBillBeforeNTSSend(_cancelCashBillBeforeNTSSend_certkey, _cancelCashBillBeforeNTSSend_corpNum, _cancelCashBillBeforeNTSSend_userID, _cancelCashBillBeforeNTSSend_mgtKey);
        System.out.println("cancelCashBillBeforeNTSSend.result=" + _cancelCashBillBeforeNTSSend__return);


        }
        {
        System.out.println("Invoking getCashBillPopUpURL...");
        java.lang.String _getCashBillPopUpURL_certkey = "";
        java.lang.String _getCashBillPopUpURL_corpNum = "";
        java.lang.String _getCashBillPopUpURL_userID = "";
        java.lang.String _getCashBillPopUpURL_pwd = "";
        java.lang.String _getCashBillPopUpURL_mgtKey = "";
        java.lang.String _getCashBillPopUpURL__return = port.getCashBillPopUpURL(_getCashBillPopUpURL_certkey, _getCashBillPopUpURL_corpNum, _getCashBillPopUpURL_userID, _getCashBillPopUpURL_pwd, _getCashBillPopUpURL_mgtKey);
        System.out.println("getCashBillPopUpURL.result=" + _getCashBillPopUpURL__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCashBillSalesListByID...");
        java.lang.String _getCashBillSalesListByID_certkey = "";
        java.lang.String _getCashBillSalesListByID_corpNum = "";
        java.lang.String _getCashBillSalesListByID_userID = "";
        java.lang.String _getCashBillSalesListByID_baseDate = "";
        int _getCashBillSalesListByID_countPerPage = 0;
        int _getCashBillSalesListByID_currentPage = 0;
        com.baroservice.ws.PagedCashBill _getCashBillSalesListByID__return = port.getCashBillSalesListByID(_getCashBillSalesListByID_certkey, _getCashBillSalesListByID_corpNum, _getCashBillSalesListByID_userID, _getCashBillSalesListByID_baseDate, _getCashBillSalesListByID_countPerPage, _getCashBillSalesListByID_currentPage);
        System.out.println("getCashBillSalesListByID.result=" + _getCashBillSalesListByID__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getDailyCashBillPurchaseList...");
        java.lang.String _getDailyCashBillPurchaseList_certkey = "";
        java.lang.String _getDailyCashBillPurchaseList_corpNum = "";
        java.lang.String _getDailyCashBillPurchaseList_userID = "";
        java.lang.String _getDailyCashBillPurchaseList_baseDate = "";
        int _getDailyCashBillPurchaseList_countPerPage = 0;
        int _getDailyCashBillPurchaseList_currentPage = 0;
        int _getDailyCashBillPurchaseList_orderDirection = 0;
        com.baroservice.ws.PagedCashBill _getDailyCashBillPurchaseList__return = port.getDailyCashBillPurchaseList(_getDailyCashBillPurchaseList_certkey, _getDailyCashBillPurchaseList_corpNum, _getDailyCashBillPurchaseList_userID, _getDailyCashBillPurchaseList_baseDate, _getDailyCashBillPurchaseList_countPerPage, _getDailyCashBillPurchaseList_currentPage, _getDailyCashBillPurchaseList_orderDirection);
        System.out.println("getDailyCashBillPurchaseList.result=" + _getDailyCashBillPurchaseList__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking getCashBillPrintURL...");
        java.lang.String _getCashBillPrintURL_certkey = "";
        java.lang.String _getCashBillPrintURL_corpNum = "";
        java.lang.String _getCashBillPrintURL_userID = "";
        java.lang.String _getCashBillPrintURL_pwd = "";
        java.lang.String _getCashBillPrintURL_mgtKey = "";
        java.lang.String _getCashBillPrintURL__return = port.getCashBillPrintURL(_getCashBillPrintURL_certkey, _getCashBillPrintURL_corpNum, _getCashBillPrintURL_userID, _getCashBillPrintURL_pwd, _getCashBillPrintURL_mgtKey);
        System.out.println("getCashBillPrintURL.result=" + _getCashBillPrintURL__return);


        }
        {
        System.out.println("Invoking sendFax...");
        java.lang.String _sendFax_certkey = "";
        java.lang.String _sendFax_corpNum = "";
        java.lang.String _sendFax_userID = "";
        java.lang.String _sendFax_mgtKey = "";
        java.lang.String _sendFax_fromFaxNumber = "";
        java.lang.String _sendFax_toFaxNumber = "";
        int _sendFax__return = port.sendFax(_sendFax_certkey, _sendFax_corpNum, _sendFax_userID, _sendFax_mgtKey, _sendFax_fromFaxNumber, _sendFax_toFaxNumber);
        System.out.println("sendFax.result=" + _sendFax__return);


        }
        {
        System.out.println("Invoking getDailyCashBillSalesList...");
        java.lang.String _getDailyCashBillSalesList_certkey = "";
        java.lang.String _getDailyCashBillSalesList_corpNum = "";
        java.lang.String _getDailyCashBillSalesList_userID = "";
        java.lang.String _getDailyCashBillSalesList_baseDate = "";
        int _getDailyCashBillSalesList_countPerPage = 0;
        int _getDailyCashBillSalesList_currentPage = 0;
        int _getDailyCashBillSalesList_orderDirection = 0;
        com.baroservice.ws.PagedCashBill _getDailyCashBillSalesList__return = port.getDailyCashBillSalesList(_getDailyCashBillSalesList_certkey, _getDailyCashBillSalesList_corpNum, _getDailyCashBillSalesList_userID, _getDailyCashBillSalesList_baseDate, _getDailyCashBillSalesList_countPerPage, _getDailyCashBillSalesList_currentPage, _getDailyCashBillSalesList_orderDirection);
        System.out.println("getDailyCashBillSalesList.result=" + _getDailyCashBillSalesList__return);


        }
        {
        System.out.println("Invoking updateCashBill...");
        java.lang.String _updateCashBill_certkey = "";
        java.lang.String _updateCashBill_corpNum = "";
        java.lang.String _updateCashBill_userID = "";
        com.baroservice.ws.CashBill _updateCashBill_invoice = new com.baroservice.ws.CashBill();
        int _updateCashBill__return = port.updateCashBill(_updateCashBill_certkey, _updateCashBill_corpNum, _updateCashBill_userID, _updateCashBill_invoice);
        System.out.println("updateCashBill.result=" + _updateCashBill__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
