package com.baroservice.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T12:00:13.446+09:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://ws.baroservice.com/", name = "BaroService_CORPSTATESoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BaroServiceCORPSTATESoap {

    /**
     * 회원사 관리자 변경
     */
    @WebMethod(operationName = "ChangeCorpManager", action = "http://ws.baroservice.com/ChangeCorpManager")
    @RequestWrapper(localName = "ChangeCorpManager", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ChangeCorpManager")
    @ResponseWrapper(localName = "ChangeCorpManagerResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.ChangeCorpManagerResponse")
    @WebResult(name = "ChangeCorpManagerResult", targetNamespace = "http://ws.baroservice.com/")
    public int changeCorpManager(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "newManagerID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String newManagerID
    );

    /**
     * 회원사 가입여부 확인
     */
    @WebMethod(operationName = "CheckCorpIsMember", action = "http://ws.baroservice.com/CheckCorpIsMember")
    @RequestWrapper(localName = "CheckCorpIsMember", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCorpIsMember")
    @ResponseWrapper(localName = "CheckCorpIsMemberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCorpIsMemberResponse")
    @WebResult(name = "CheckCorpIsMemberResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkCorpIsMember(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String checkCorpNum
    );

    /**
     * 회원사 사용자 추가
     */
    @WebMethod(operationName = "AddUserToCorp", action = "http://ws.baroservice.com/AddUserToCorp")
    @RequestWrapper(localName = "AddUserToCorp", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.AddUserToCorp")
    @ResponseWrapper(localName = "AddUserToCorpResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.AddUserToCorpResponse")
    @WebResult(name = "AddUserToCorpResult", targetNamespace = "http://ws.baroservice.com/")
    public int addUserToCorp(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email
    );

    /**
     * 회원사 사용자 수정
     */
    @WebMethod(operationName = "UpdateUserInfo", action = "http://ws.baroservice.com/UpdateUserInfo")
    @RequestWrapper(localName = "UpdateUserInfo", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserInfo")
    @ResponseWrapper(localName = "UpdateUserInfoResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserInfoResponse")
    @WebResult(name = "UpdateUserInfoResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateUserInfo(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade
    );

    /**
     * 휴폐업 조회 (대량)
     */
    @WebMethod(operationName = "GetCorpStates", action = "http://ws.baroservice.com/GetCorpStates")
    @RequestWrapper(localName = "GetCorpStates", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpStates")
    @ResponseWrapper(localName = "GetCorpStatesResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpStatesResponse")
    @WebResult(name = "GetCorpStatesResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfCorpState getCorpStates(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNumList", targetNamespace = "http://ws.baroservice.com/")
        com.baroservice.ws.ArrayOfString checkCorpNumList
    );

    /**
     * 휴폐업 조회 (단건)
     */
    @WebMethod(operationName = "GetCorpState", action = "http://ws.baroservice.com/GetCorpState")
    @RequestWrapper(localName = "GetCorpState", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpState")
    @ResponseWrapper(localName = "GetCorpStateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpStateResponse")
    @WebResult(name = "GetCorpStateResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.CorpState getCorpState(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String checkCorpNum
    );

    /**
     * 바로빌 메인화면 URL 반환
     */
    @WebMethod(operationName = "GetLoginURL", action = "http://ws.baroservice.com/GetLoginURL")
    @RequestWrapper(localName = "GetLoginURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetLoginURL")
    @ResponseWrapper(localName = "GetLoginURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetLoginURLResponse")
    @WebResult(name = "GetLoginURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getLoginURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 등록한 공인인증서 등록일시 확인
     */
    @WebMethod(operationName = "GetCertificateRegistDate", action = "http://ws.baroservice.com/GetCertificateRegistDate")
    @RequestWrapper(localName = "GetCertificateRegistDate", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistDate")
    @ResponseWrapper(localName = "GetCertificateRegistDateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistDateResponse")
    @WebResult(name = "GetCertificateRegistDateResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateRegistDate(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 문자 발신번호 등록여부 확인
     */
    @WebMethod(operationName = "CheckSMSFromNumber", action = "http://ws.baroservice.com/CheckSMSFromNumber")
    @RequestWrapper(localName = "CheckSMSFromNumber", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckSMSFromNumber")
    @ResponseWrapper(localName = "CheckSMSFromNumberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckSMSFromNumberResponse")
    @WebResult(name = "CheckSMSFromNumberResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkSMSFromNumber(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber
    );

    /**
     * 문자 발신번호 추가
     */
    @WebMethod(operationName = "RegistSMSFromNumber", action = "http://ws.baroservice.com/RegistSMSFromNumber")
    @RequestWrapper(localName = "RegistSMSFromNumber", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistSMSFromNumber")
    @ResponseWrapper(localName = "RegistSMSFromNumberResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistSMSFromNumberResponse")
    @WebResult(name = "RegistSMSFromNumberResult", targetNamespace = "http://ws.baroservice.com/")
    public int registSMSFromNumber(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "FromNumber", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String fromNumber
    );

    /**
     * 과금가능 여부 확인
     */
    @WebMethod(operationName = "CheckChargeable", action = "http://ws.baroservice.com/CheckChargeable")
    @RequestWrapper(localName = "CheckChargeable", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckChargeable")
    @ResponseWrapper(localName = "CheckChargeableResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckChargeableResponse")
    @WebResult(name = "CheckChargeableResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkChargeable(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CType", targetNamespace = "http://ws.baroservice.com/")
        int cType,
        @WebParam(name = "DocType", targetNamespace = "http://ws.baroservice.com/")
        int docType
    );

    /**
     * Ping
     */
    @WebMethod(operationName = "Ping", action = "http://ws.baroservice.com/Ping")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.PingResponse")
    public void ping();

    /**
     * 회원사 충전잔액 확인
     */
    @WebMethod(operationName = "GetBalanceCostAmount", action = "http://ws.baroservice.com/GetBalanceCostAmount")
    @RequestWrapper(localName = "GetBalanceCostAmount", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmount")
    @ResponseWrapper(localName = "GetBalanceCostAmountResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountResponse")
    @WebResult(name = "GetBalanceCostAmountResult", targetNamespace = "http://ws.baroservice.com/")
    public long getBalanceCostAmount(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 바로빌 링크 연결 URL확인
     */
    @WebMethod(operationName = "GetBaroBillURL", action = "http://ws.baroservice.com/GetBaroBillURL")
    @RequestWrapper(localName = "GetBaroBillURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBaroBillURL")
    @ResponseWrapper(localName = "GetBaroBillURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBaroBillURLResponse")
    @WebResult(name = "GetBaroBillURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getBaroBillURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "TOGO", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String togo
    );

    /**
     * 휴폐업조회 서비스 신청 URL
     */
    @WebMethod(operationName = "GetCorpStateScrapRequestURL", action = "http://ws.baroservice.com/GetCorpStateScrapRequestURL")
    @RequestWrapper(localName = "GetCorpStateScrapRequestURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpStateScrapRequestURL")
    @ResponseWrapper(localName = "GetCorpStateScrapRequestURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpStateScrapRequestURLResponse")
    @WebResult(name = "GetCorpStateScrapRequestURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCorpStateScrapRequestURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 오류코드의 상세내용 반환
     */
    @WebMethod(operationName = "GetErrString", action = "http://ws.baroservice.com/GetErrString")
    @RequestWrapper(localName = "GetErrString", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetErrString")
    @ResponseWrapper(localName = "GetErrStringResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetErrStringResponse")
    @WebResult(name = "GetErrStringResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getErrString(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "ErrCode", targetNamespace = "http://ws.baroservice.com/")
        int errCode
    );

    /**
     * 등록한 공인인증서 상태 확인
     */
    @WebMethod(operationName = "CheckCERTIsValid", action = "http://ws.baroservice.com/CheckCERTIsValid")
    @RequestWrapper(localName = "CheckCERTIsValid", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCERTIsValid")
    @ResponseWrapper(localName = "CheckCERTIsValidResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.CheckCERTIsValidResponse")
    @WebResult(name = "CheckCERTIsValidResult", targetNamespace = "http://ws.baroservice.com/")
    public int checkCERTIsValid(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 회원사 담당자 목록확인
     */
    @WebMethod(operationName = "GetCorpMemberContacts", action = "http://ws.baroservice.com/GetCorpMemberContacts")
    @RequestWrapper(localName = "GetCorpMemberContacts", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpMemberContacts")
    @ResponseWrapper(localName = "GetCorpMemberContactsResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCorpMemberContactsResponse")
    @WebResult(name = "GetCorpMemberContactsResult", targetNamespace = "http://ws.baroservice.com/")
    public com.baroservice.ws.ArrayOfContact getCorpMemberContacts(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CheckCorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String checkCorpNum
    );

    /**
     * 문자 발신번호 관리 URL 반환
     */
    @WebMethod(operationName = "GetSMSFromNumberURL", action = "http://ws.baroservice.com/GetSMSFromNumberURL")
    @RequestWrapper(localName = "GetSMSFromNumberURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetSMSFromNumberURL")
    @ResponseWrapper(localName = "GetSMSFromNumberURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetSMSFromNumberURLResponse")
    @WebResult(name = "GetSMSFromNumberURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getSMSFromNumberURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 등록한 공인인증서 만료일 확인
     */
    @WebMethod(operationName = "GetCertificateExpireDate", action = "http://ws.baroservice.com/GetCertificateExpireDate")
    @RequestWrapper(localName = "GetCertificateExpireDate", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateExpireDate")
    @ResponseWrapper(localName = "GetCertificateExpireDateResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateExpireDateResponse")
    @WebResult(name = "GetCertificateExpireDateResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateExpireDate(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum
    );

    /**
     * 회원사 사용자 비밀번호 변경
     */
    @WebMethod(operationName = "UpdateUserPWD", action = "http://ws.baroservice.com/UpdateUserPWD")
    @RequestWrapper(localName = "UpdateUserPWD", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserPWD")
    @ResponseWrapper(localName = "UpdateUserPWDResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateUserPWDResponse")
    @WebResult(name = "UpdateUserPWDResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateUserPWD(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "newPWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String newPWD
    );

    /**
     * 포인트 충전 URL 반환
     */
    @WebMethod(operationName = "GetCashChargeURL", action = "http://ws.baroservice.com/GetCashChargeURL")
    @RequestWrapper(localName = "GetCashChargeURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCashChargeURL")
    @ResponseWrapper(localName = "GetCashChargeURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCashChargeURLResponse")
    @WebResult(name = "GetCashChargeURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCashChargeURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 공인인증서 등록 URL 확인
     */
    @WebMethod(operationName = "GetCertificateRegistURL", action = "http://ws.baroservice.com/GetCertificateRegistURL")
    @RequestWrapper(localName = "GetCertificateRegistURL", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistURL")
    @ResponseWrapper(localName = "GetCertificateRegistURLResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetCertificateRegistURLResponse")
    @WebResult(name = "GetCertificateRegistURLResult", targetNamespace = "http://ws.baroservice.com/")
    public java.lang.String getCertificateRegistURL(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd
    );

    /**
     * 회원사 수정
     */
    @WebMethod(operationName = "UpdateCorpInfo", action = "http://ws.baroservice.com/UpdateCorpInfo")
    @RequestWrapper(localName = "UpdateCorpInfo", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateCorpInfo")
    @ResponseWrapper(localName = "UpdateCorpInfoResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.UpdateCorpInfoResponse")
    @WebResult(name = "UpdateCorpInfoResult", targetNamespace = "http://ws.baroservice.com/")
    public int updateCorpInfo(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CorpName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpName,
        @WebParam(name = "CEOName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String ceoName,
        @WebParam(name = "BizType", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizType,
        @WebParam(name = "BizClass", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizClass,
        @WebParam(name = "PostNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String postNum,
        @WebParam(name = "Addr1", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr1,
        @WebParam(name = "Addr2", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr2
    );

    /**
     * 회원사 가입
     */
    @WebMethod(operationName = "RegistCorp", action = "http://ws.baroservice.com/RegistCorp")
    @RequestWrapper(localName = "RegistCorp", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistCorp")
    @ResponseWrapper(localName = "RegistCorpResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.RegistCorpResponse")
    @WebResult(name = "RegistCorpResult", targetNamespace = "http://ws.baroservice.com/")
    public int registCorp(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "CorpName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpName,
        @WebParam(name = "CEOName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String ceoName,
        @WebParam(name = "BizType", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizType,
        @WebParam(name = "BizClass", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String bizClass,
        @WebParam(name = "PostNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String postNum,
        @WebParam(name = "Addr1", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr1,
        @WebParam(name = "Addr2", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String addr2,
        @WebParam(name = "MemberName", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String memberName,
        @WebParam(name = "JuminNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String juminNum,
        @WebParam(name = "ID", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String id,
        @WebParam(name = "PWD", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String pwd,
        @WebParam(name = "Grade", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String grade,
        @WebParam(name = "TEL", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String tel,
        @WebParam(name = "HP", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String hp,
        @WebParam(name = "Email", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String email
    );

    /**
     * 연동사 충전잔액 확인
     */
    @WebMethod(operationName = "GetBalanceCostAmountOfInterOP", action = "http://ws.baroservice.com/GetBalanceCostAmountOfInterOP")
    @RequestWrapper(localName = "GetBalanceCostAmountOfInterOP", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountOfInterOP")
    @ResponseWrapper(localName = "GetBalanceCostAmountOfInterOPResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetBalanceCostAmountOfInterOPResponse")
    @WebResult(name = "GetBalanceCostAmountOfInterOPResult", targetNamespace = "http://ws.baroservice.com/")
    public long getBalanceCostAmountOfInterOP(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey
    );

    /**
     * 단가 확인
     */
    @WebMethod(operationName = "GetChargeUnitCost", action = "http://ws.baroservice.com/GetChargeUnitCost")
    @RequestWrapper(localName = "GetChargeUnitCost", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetChargeUnitCost")
    @ResponseWrapper(localName = "GetChargeUnitCostResponse", targetNamespace = "http://ws.baroservice.com/", className = "com.baroservice.ws.GetChargeUnitCostResponse")
    @WebResult(name = "GetChargeUnitCostResult", targetNamespace = "http://ws.baroservice.com/")
    public int getChargeUnitCost(
        @WebParam(name = "CERTKEY", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String certkey,
        @WebParam(name = "CorpNum", targetNamespace = "http://ws.baroservice.com/")
        java.lang.String corpNum,
        @WebParam(name = "ChargeCode", targetNamespace = "http://ws.baroservice.com/")
        int chargeCode
    );
}
