package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 전자문서 연동서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:07.857+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_EDOC",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/edoc.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceEDOC extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_EDOC");
    public final static QName BaroServiceEDOCSoap12 = new QName("http://ws.baroservice.com/", "BaroService_EDOCSoap12");
    public final static QName BaroServiceEDOCSoap = new QName("http://ws.baroservice.com/", "BaroService_EDOCSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/edoc.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceEDOC.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/edoc.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceEDOC(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceEDOC(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceEDOC() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceEDOC(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceEDOC(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceEDOC(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceEDOCSoap
     */
    @WebEndpoint(name = "BaroService_EDOCSoap12")
    public BaroServiceEDOCSoap getBaroServiceEDOCSoap12() {
        return super.getPort(BaroServiceEDOCSoap12, BaroServiceEDOCSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceEDOCSoap
     */
    @WebEndpoint(name = "BaroService_EDOCSoap12")
    public BaroServiceEDOCSoap getBaroServiceEDOCSoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceEDOCSoap12, BaroServiceEDOCSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceEDOCSoap
     */
    @WebEndpoint(name = "BaroService_EDOCSoap")
    public BaroServiceEDOCSoap getBaroServiceEDOCSoap() {
        return super.getPort(BaroServiceEDOCSoap, BaroServiceEDOCSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceEDOCSoap
     */
    @WebEndpoint(name = "BaroService_EDOCSoap")
    public BaroServiceEDOCSoap getBaroServiceEDOCSoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceEDOCSoap, BaroServiceEDOCSoap.class, features);
    }

}
