package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 SMS 발송서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:31.394+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_SMS",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/sms.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceSMS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_SMS");
    public final static QName BaroServiceSMSSoap = new QName("http://ws.baroservice.com/", "BaroService_SMSSoap");
    public final static QName BaroServiceSMSSoap12 = new QName("http://ws.baroservice.com/", "BaroService_SMSSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/sms.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceSMS.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/sms.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceSMS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceSMS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceSMS() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceSMS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceSMS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceSMS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceSMSSoap
     */
    @WebEndpoint(name = "BaroService_SMSSoap")
    public BaroServiceSMSSoap getBaroServiceSMSSoap() {
        return super.getPort(BaroServiceSMSSoap, BaroServiceSMSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceSMSSoap
     */
    @WebEndpoint(name = "BaroService_SMSSoap")
    public BaroServiceSMSSoap getBaroServiceSMSSoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceSMSSoap, BaroServiceSMSSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceSMSSoap
     */
    @WebEndpoint(name = "BaroService_SMSSoap12")
    public BaroServiceSMSSoap getBaroServiceSMSSoap12() {
        return super.getPort(BaroServiceSMSSoap12, BaroServiceSMSSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceSMSSoap
     */
    @WebEndpoint(name = "BaroService_SMSSoap12")
    public BaroServiceSMSSoap getBaroServiceSMSSoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceSMSSoap12, BaroServiceSMSSoap.class, features);
    }

}
