package com.baroservice.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * 바로빌 현금영수증 연동서비스
 *
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:18.417+09:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "BaroService_CASHBILL",
                  wsdlLocation = "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/cashbill.asmx",
                  targetNamespace = "http://ws.baroservice.com/")
public class BaroServiceCASHBILL extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.baroservice.com/", "BaroService_CASHBILL");
    public final static QName BaroServiceCASHBILLSoap = new QName("http://ws.baroservice.com/", "BaroService_CASHBILLSoap");
    public final static QName BaroServiceCASHBILLSoap12 = new QName("http://ws.baroservice.com/", "BaroService_CASHBILLSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/cashbill.asmx");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BaroServiceCASHBILL.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/D:/com.knet.product.barobill/barobill-api-v3-sample-java/barobill-api-cxf/src/main/java/com/baroservice/ws/cashbill.asmx");
        }
        WSDL_LOCATION = url;
    }

    public BaroServiceCASHBILL(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BaroServiceCASHBILL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BaroServiceCASHBILL() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BaroServiceCASHBILL(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BaroServiceCASHBILL(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BaroServiceCASHBILL(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BaroServiceCASHBILLSoap
     */
    @WebEndpoint(name = "BaroService_CASHBILLSoap")
    public BaroServiceCASHBILLSoap getBaroServiceCASHBILLSoap() {
        return super.getPort(BaroServiceCASHBILLSoap, BaroServiceCASHBILLSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceCASHBILLSoap
     */
    @WebEndpoint(name = "BaroService_CASHBILLSoap")
    public BaroServiceCASHBILLSoap getBaroServiceCASHBILLSoap(WebServiceFeature... features) {
        return super.getPort(BaroServiceCASHBILLSoap, BaroServiceCASHBILLSoap.class, features);
    }


    /**
     *
     * @return
     *     returns BaroServiceCASHBILLSoap
     */
    @WebEndpoint(name = "BaroService_CASHBILLSoap12")
    public BaroServiceCASHBILLSoap getBaroServiceCASHBILLSoap12() {
        return super.getPort(BaroServiceCASHBILLSoap12, BaroServiceCASHBILLSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BaroServiceCASHBILLSoap
     */
    @WebEndpoint(name = "BaroService_CASHBILLSoap12")
    public BaroServiceCASHBILLSoap getBaroServiceCASHBILLSoap12(WebServiceFeature... features) {
        return super.getPort(BaroServiceCASHBILLSoap12, BaroServiceCASHBILLSoap.class, features);
    }

}
