
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:50.554+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceCARDSoap_BaroServiceCARDSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_CARD");

    private BaroServiceCARDSoap_BaroServiceCARDSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceCARD.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceCARD ss = new BaroServiceCARD(wsdlURL, SERVICE_NAME);
        BaroServiceCARDSoap port = ss.getBaroServiceCARDSoap12();

        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking getCard...");
        java.lang.String _getCard_certkey = "";
        java.lang.String _getCard_corpNum = "";
        com.baroservice.ws.ArrayOfCard _getCard__return = port.getCard(_getCard_certkey, _getCard_corpNum);
        System.out.println("getCard.result=" + _getCard__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking getCardLog...");
        java.lang.String _getCardLog_certkey = "";
        java.lang.String _getCardLog_corpNum = "";
        java.lang.String _getCardLog_id = "";
        java.lang.String _getCardLog_cardNum = "";
        java.lang.String _getCardLog_baseDate = "";
        int _getCardLog_countPerPage = 0;
        int _getCardLog_currentPage = 0;
        com.baroservice.ws.PagedCardLog _getCardLog__return = port.getCardLog(_getCardLog_certkey, _getCardLog_corpNum, _getCardLog_id, _getCardLog_cardNum, _getCardLog_baseDate, _getCardLog_countPerPage, _getCardLog_currentPage);
        System.out.println("getCardLog.result=" + _getCardLog__return);


        }
        {
        System.out.println("Invoking getCardLogEx...");
        java.lang.String _getCardLogEx_certkey = "";
        java.lang.String _getCardLogEx_corpNum = "";
        java.lang.String _getCardLogEx_id = "";
        java.lang.String _getCardLogEx_cardNum = "";
        java.lang.String _getCardLogEx_baseDate = "";
        int _getCardLogEx_countPerPage = 0;
        int _getCardLogEx_currentPage = 0;
        com.baroservice.ws.PagedCardLogEx _getCardLogEx__return = port.getCardLogEx(_getCardLogEx_certkey, _getCardLogEx_corpNum, _getCardLogEx_id, _getCardLogEx_cardNum, _getCardLogEx_baseDate, _getCardLogEx_countPerPage, _getCardLogEx_currentPage);
        System.out.println("getCardLogEx.result=" + _getCardLogEx__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking getPeriodCardLog...");
        java.lang.String _getPeriodCardLog_certkey = "";
        java.lang.String _getPeriodCardLog_corpNum = "";
        java.lang.String _getPeriodCardLog_id = "";
        java.lang.String _getPeriodCardLog_cardNum = "";
        java.lang.String _getPeriodCardLog_startDate = "";
        java.lang.String _getPeriodCardLog_endDate = "";
        int _getPeriodCardLog_countPerPage = 0;
        int _getPeriodCardLog_currentPage = 0;
        int _getPeriodCardLog_orderDirection = 0;
        com.baroservice.ws.PagedCardLog _getPeriodCardLog__return = port.getPeriodCardLog(_getPeriodCardLog_certkey, _getPeriodCardLog_corpNum, _getPeriodCardLog_id, _getPeriodCardLog_cardNum, _getPeriodCardLog_startDate, _getPeriodCardLog_endDate, _getPeriodCardLog_countPerPage, _getPeriodCardLog_currentPage, _getPeriodCardLog_orderDirection);
        System.out.println("getPeriodCardLog.result=" + _getPeriodCardLog__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getDailyCardLogEx...");
        java.lang.String _getDailyCardLogEx_certkey = "";
        java.lang.String _getDailyCardLogEx_corpNum = "";
        java.lang.String _getDailyCardLogEx_id = "";
        java.lang.String _getDailyCardLogEx_cardNum = "";
        java.lang.String _getDailyCardLogEx_baseDate = "";
        int _getDailyCardLogEx_countPerPage = 0;
        int _getDailyCardLogEx_currentPage = 0;
        int _getDailyCardLogEx_orderDirection = 0;
        com.baroservice.ws.PagedCardLogEx _getDailyCardLogEx__return = port.getDailyCardLogEx(_getDailyCardLogEx_certkey, _getDailyCardLogEx_corpNum, _getDailyCardLogEx_id, _getDailyCardLogEx_cardNum, _getDailyCardLogEx_baseDate, _getDailyCardLogEx_countPerPage, _getDailyCardLogEx_currentPage, _getDailyCardLogEx_orderDirection);
        System.out.println("getDailyCardLogEx.result=" + _getDailyCardLogEx__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getCardLogURL...");
        java.lang.String _getCardLogURL_certkey = "";
        java.lang.String _getCardLogURL_corpNum = "";
        java.lang.String _getCardLogURL_id = "";
        java.lang.String _getCardLogURL_pwd = "";
        java.lang.String _getCardLogURL__return = port.getCardLogURL(_getCardLogURL_certkey, _getCardLogURL_corpNum, _getCardLogURL_id, _getCardLogURL_pwd);
        System.out.println("getCardLogURL.result=" + _getCardLogURL__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getCardManagementURL...");
        java.lang.String _getCardManagementURL_certkey = "";
        java.lang.String _getCardManagementURL_corpNum = "";
        java.lang.String _getCardManagementURL_id = "";
        java.lang.String _getCardManagementURL_pwd = "";
        java.lang.String _getCardManagementURL__return = port.getCardManagementURL(_getCardManagementURL_certkey, _getCardManagementURL_corpNum, _getCardManagementURL_id, _getCardManagementURL_pwd);
        System.out.println("getCardManagementURL.result=" + _getCardManagementURL__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking getCardScrapRequestURL...");
        java.lang.String _getCardScrapRequestURL_certkey = "";
        java.lang.String _getCardScrapRequestURL_corpNum = "";
        java.lang.String _getCardScrapRequestURL_id = "";
        java.lang.String _getCardScrapRequestURL_pwd = "";
        java.lang.String _getCardScrapRequestURL__return = port.getCardScrapRequestURL(_getCardScrapRequestURL_certkey, _getCardScrapRequestURL_corpNum, _getCardScrapRequestURL_id, _getCardScrapRequestURL_pwd);
        System.out.println("getCardScrapRequestURL.result=" + _getCardScrapRequestURL__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking getMonthlyCardLogEx...");
        java.lang.String _getMonthlyCardLogEx_certkey = "";
        java.lang.String _getMonthlyCardLogEx_corpNum = "";
        java.lang.String _getMonthlyCardLogEx_id = "";
        java.lang.String _getMonthlyCardLogEx_cardNum = "";
        java.lang.String _getMonthlyCardLogEx_baseMonth = "";
        int _getMonthlyCardLogEx_countPerPage = 0;
        int _getMonthlyCardLogEx_currentPage = 0;
        int _getMonthlyCardLogEx_orderDirection = 0;
        com.baroservice.ws.PagedCardLogEx _getMonthlyCardLogEx__return = port.getMonthlyCardLogEx(_getMonthlyCardLogEx_certkey, _getMonthlyCardLogEx_corpNum, _getMonthlyCardLogEx_id, _getMonthlyCardLogEx_cardNum, _getMonthlyCardLogEx_baseMonth, _getMonthlyCardLogEx_countPerPage, _getMonthlyCardLogEx_currentPage, _getMonthlyCardLogEx_orderDirection);
        System.out.println("getMonthlyCardLogEx.result=" + _getMonthlyCardLogEx__return);


        }
        {
        System.out.println("Invoking getMonthlyCardLog...");
        java.lang.String _getMonthlyCardLog_certkey = "";
        java.lang.String _getMonthlyCardLog_corpNum = "";
        java.lang.String _getMonthlyCardLog_id = "";
        java.lang.String _getMonthlyCardLog_cardNum = "";
        java.lang.String _getMonthlyCardLog_baseMonth = "";
        int _getMonthlyCardLog_countPerPage = 0;
        int _getMonthlyCardLog_currentPage = 0;
        int _getMonthlyCardLog_orderDirection = 0;
        com.baroservice.ws.PagedCardLog _getMonthlyCardLog__return = port.getMonthlyCardLog(_getMonthlyCardLog_certkey, _getMonthlyCardLog_corpNum, _getMonthlyCardLog_id, _getMonthlyCardLog_cardNum, _getMonthlyCardLog_baseMonth, _getMonthlyCardLog_countPerPage, _getMonthlyCardLog_currentPage, _getMonthlyCardLog_orderDirection);
        System.out.println("getMonthlyCardLog.result=" + _getMonthlyCardLog__return);


        }
        {
        System.out.println("Invoking getPeriodCardLogEx...");
        java.lang.String _getPeriodCardLogEx_certkey = "";
        java.lang.String _getPeriodCardLogEx_corpNum = "";
        java.lang.String _getPeriodCardLogEx_id = "";
        java.lang.String _getPeriodCardLogEx_cardNum = "";
        java.lang.String _getPeriodCardLogEx_startDate = "";
        java.lang.String _getPeriodCardLogEx_endDate = "";
        int _getPeriodCardLogEx_countPerPage = 0;
        int _getPeriodCardLogEx_currentPage = 0;
        int _getPeriodCardLogEx_orderDirection = 0;
        com.baroservice.ws.PagedCardLogEx _getPeriodCardLogEx__return = port.getPeriodCardLogEx(_getPeriodCardLogEx_certkey, _getPeriodCardLogEx_corpNum, _getPeriodCardLogEx_id, _getPeriodCardLogEx_cardNum, _getPeriodCardLogEx_startDate, _getPeriodCardLogEx_endDate, _getPeriodCardLogEx_countPerPage, _getPeriodCardLogEx_currentPage, _getPeriodCardLogEx_orderDirection);
        System.out.println("getPeriodCardLogEx.result=" + _getPeriodCardLogEx__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getDailyCardLog...");
        java.lang.String _getDailyCardLog_certkey = "";
        java.lang.String _getDailyCardLog_corpNum = "";
        java.lang.String _getDailyCardLog_id = "";
        java.lang.String _getDailyCardLog_cardNum = "";
        java.lang.String _getDailyCardLog_baseDate = "";
        int _getDailyCardLog_countPerPage = 0;
        int _getDailyCardLog_currentPage = 0;
        int _getDailyCardLog_orderDirection = 0;
        com.baroservice.ws.PagedCardLog _getDailyCardLog__return = port.getDailyCardLog(_getDailyCardLog_certkey, _getDailyCardLog_corpNum, _getDailyCardLog_id, _getDailyCardLog_cardNum, _getDailyCardLog_baseDate, _getDailyCardLog_countPerPage, _getDailyCardLog_currentPage, _getDailyCardLog_orderDirection);
        System.out.println("getDailyCardLog.result=" + _getDailyCardLog__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
