
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T12:00:03.604+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceBANKACCOUNTSoap_BaroServiceBANKACCOUNTSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_BANKACCOUNT");

    private BaroServiceBANKACCOUNTSoap_BaroServiceBANKACCOUNTSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceBANKACCOUNT.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceBANKACCOUNT ss = new BaroServiceBANKACCOUNT(wsdlURL, SERVICE_NAME);
        BaroServiceBANKACCOUNTSoap port = ss.getBaroServiceBANKACCOUNTSoap();

        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking getBankAccountEx...");
        java.lang.String _getBankAccountEx_certkey = "";
        java.lang.String _getBankAccountEx_corpNum = "";
        int _getBankAccountEx_availOnly = 0;
        com.baroservice.ws.ArrayOfBankAccount _getBankAccountEx__return = port.getBankAccountEx(_getBankAccountEx_certkey, _getBankAccountEx_corpNum, _getBankAccountEx_availOnly);
        System.out.println("getBankAccountEx.result=" + _getBankAccountEx__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getBankAccountScrapRequestURL...");
        java.lang.String _getBankAccountScrapRequestURL_certkey = "";
        java.lang.String _getBankAccountScrapRequestURL_corpNum = "";
        java.lang.String _getBankAccountScrapRequestURL_id = "";
        java.lang.String _getBankAccountScrapRequestURL_pwd = "";
        java.lang.String _getBankAccountScrapRequestURL__return = port.getBankAccountScrapRequestURL(_getBankAccountScrapRequestURL_certkey, _getBankAccountScrapRequestURL_corpNum, _getBankAccountScrapRequestURL_id, _getBankAccountScrapRequestURL_pwd);
        System.out.println("getBankAccountScrapRequestURL.result=" + _getBankAccountScrapRequestURL__return);


        }
        {
        System.out.println("Invoking getMonthlyBankAccountLog...");
        java.lang.String _getMonthlyBankAccountLog_certkey = "";
        java.lang.String _getMonthlyBankAccountLog_corpNum = "";
        java.lang.String _getMonthlyBankAccountLog_id = "";
        java.lang.String _getMonthlyBankAccountLog_bankAccountNum = "";
        java.lang.String _getMonthlyBankAccountLog_baseMonth = "";
        int _getMonthlyBankAccountLog_countPerPage = 0;
        int _getMonthlyBankAccountLog_currentPage = 0;
        int _getMonthlyBankAccountLog_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLog _getMonthlyBankAccountLog__return = port.getMonthlyBankAccountLog(_getMonthlyBankAccountLog_certkey, _getMonthlyBankAccountLog_corpNum, _getMonthlyBankAccountLog_id, _getMonthlyBankAccountLog_bankAccountNum, _getMonthlyBankAccountLog_baseMonth, _getMonthlyBankAccountLog_countPerPage, _getMonthlyBankAccountLog_currentPage, _getMonthlyBankAccountLog_orderDirection);
        System.out.println("getMonthlyBankAccountLog.result=" + _getMonthlyBankAccountLog__return);


        }
        {
        System.out.println("Invoking getBankAccountLog...");
        java.lang.String _getBankAccountLog_certkey = "";
        java.lang.String _getBankAccountLog_corpNum = "";
        java.lang.String _getBankAccountLog_id = "";
        java.lang.String _getBankAccountLog_bankAccountNum = "";
        java.lang.String _getBankAccountLog_baseDate = "";
        int _getBankAccountLog_countPerPage = 0;
        int _getBankAccountLog_currentPage = 0;
        com.baroservice.ws.PagedBankAccountLog _getBankAccountLog__return = port.getBankAccountLog(_getBankAccountLog_certkey, _getBankAccountLog_corpNum, _getBankAccountLog_id, _getBankAccountLog_bankAccountNum, _getBankAccountLog_baseDate, _getBankAccountLog_countPerPage, _getBankAccountLog_currentPage);
        System.out.println("getBankAccountLog.result=" + _getBankAccountLog__return);


        }
        {
        System.out.println("Invoking getPeriodBankAccountLog...");
        java.lang.String _getPeriodBankAccountLog_certkey = "";
        java.lang.String _getPeriodBankAccountLog_corpNum = "";
        java.lang.String _getPeriodBankAccountLog_id = "";
        java.lang.String _getPeriodBankAccountLog_bankAccountNum = "";
        java.lang.String _getPeriodBankAccountLog_startDate = "";
        java.lang.String _getPeriodBankAccountLog_endDate = "";
        int _getPeriodBankAccountLog_countPerPage = 0;
        int _getPeriodBankAccountLog_currentPage = 0;
        int _getPeriodBankAccountLog_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLog _getPeriodBankAccountLog__return = port.getPeriodBankAccountLog(_getPeriodBankAccountLog_certkey, _getPeriodBankAccountLog_corpNum, _getPeriodBankAccountLog_id, _getPeriodBankAccountLog_bankAccountNum, _getPeriodBankAccountLog_startDate, _getPeriodBankAccountLog_endDate, _getPeriodBankAccountLog_countPerPage, _getPeriodBankAccountLog_currentPage, _getPeriodBankAccountLog_orderDirection);
        System.out.println("getPeriodBankAccountLog.result=" + _getPeriodBankAccountLog__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking getDailyBankAccountLogEx...");
        java.lang.String _getDailyBankAccountLogEx_certkey = "";
        java.lang.String _getDailyBankAccountLogEx_corpNum = "";
        java.lang.String _getDailyBankAccountLogEx_id = "";
        java.lang.String _getDailyBankAccountLogEx_bankAccountNum = "";
        java.lang.String _getDailyBankAccountLogEx_baseDate = "";
        int _getDailyBankAccountLogEx_countPerPage = 0;
        int _getDailyBankAccountLogEx_currentPage = 0;
        int _getDailyBankAccountLogEx_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLogEx _getDailyBankAccountLogEx__return = port.getDailyBankAccountLogEx(_getDailyBankAccountLogEx_certkey, _getDailyBankAccountLogEx_corpNum, _getDailyBankAccountLogEx_id, _getDailyBankAccountLogEx_bankAccountNum, _getDailyBankAccountLogEx_baseDate, _getDailyBankAccountLogEx_countPerPage, _getDailyBankAccountLogEx_currentPage, _getDailyBankAccountLogEx_orderDirection);
        System.out.println("getDailyBankAccountLogEx.result=" + _getDailyBankAccountLogEx__return);


        }
        {
        System.out.println("Invoking getPeriodBankAccountLogEx...");
        java.lang.String _getPeriodBankAccountLogEx_certkey = "";
        java.lang.String _getPeriodBankAccountLogEx_corpNum = "";
        java.lang.String _getPeriodBankAccountLogEx_id = "";
        java.lang.String _getPeriodBankAccountLogEx_bankAccountNum = "";
        java.lang.String _getPeriodBankAccountLogEx_startDate = "";
        java.lang.String _getPeriodBankAccountLogEx_endDate = "";
        int _getPeriodBankAccountLogEx_countPerPage = 0;
        int _getPeriodBankAccountLogEx_currentPage = 0;
        int _getPeriodBankAccountLogEx_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLogEx _getPeriodBankAccountLogEx__return = port.getPeriodBankAccountLogEx(_getPeriodBankAccountLogEx_certkey, _getPeriodBankAccountLogEx_corpNum, _getPeriodBankAccountLogEx_id, _getPeriodBankAccountLogEx_bankAccountNum, _getPeriodBankAccountLogEx_startDate, _getPeriodBankAccountLogEx_endDate, _getPeriodBankAccountLogEx_countPerPage, _getPeriodBankAccountLogEx_currentPage, _getPeriodBankAccountLogEx_orderDirection);
        System.out.println("getPeriodBankAccountLogEx.result=" + _getPeriodBankAccountLogEx__return);


        }
        {
        System.out.println("Invoking getBankAccount...");
        java.lang.String _getBankAccount_certkey = "";
        java.lang.String _getBankAccount_corpNum = "";
        com.baroservice.ws.ArrayOfBankAccount _getBankAccount__return = port.getBankAccount(_getBankAccount_certkey, _getBankAccount_corpNum);
        System.out.println("getBankAccount.result=" + _getBankAccount__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getBankAccountManagementURL...");
        java.lang.String _getBankAccountManagementURL_certkey = "";
        java.lang.String _getBankAccountManagementURL_corpNum = "";
        java.lang.String _getBankAccountManagementURL_id = "";
        java.lang.String _getBankAccountManagementURL_pwd = "";
        java.lang.String _getBankAccountManagementURL__return = port.getBankAccountManagementURL(_getBankAccountManagementURL_certkey, _getBankAccountManagementURL_corpNum, _getBankAccountManagementURL_id, _getBankAccountManagementURL_pwd);
        System.out.println("getBankAccountManagementURL.result=" + _getBankAccountManagementURL__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking getDailyBankAccountLog...");
        java.lang.String _getDailyBankAccountLog_certkey = "";
        java.lang.String _getDailyBankAccountLog_corpNum = "";
        java.lang.String _getDailyBankAccountLog_id = "";
        java.lang.String _getDailyBankAccountLog_bankAccountNum = "";
        java.lang.String _getDailyBankAccountLog_baseDate = "";
        int _getDailyBankAccountLog_countPerPage = 0;
        int _getDailyBankAccountLog_currentPage = 0;
        int _getDailyBankAccountLog_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLog _getDailyBankAccountLog__return = port.getDailyBankAccountLog(_getDailyBankAccountLog_certkey, _getDailyBankAccountLog_corpNum, _getDailyBankAccountLog_id, _getDailyBankAccountLog_bankAccountNum, _getDailyBankAccountLog_baseDate, _getDailyBankAccountLog_countPerPage, _getDailyBankAccountLog_currentPage, _getDailyBankAccountLog_orderDirection);
        System.out.println("getDailyBankAccountLog.result=" + _getDailyBankAccountLog__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getBankAccountLogEx...");
        java.lang.String _getBankAccountLogEx_certkey = "";
        java.lang.String _getBankAccountLogEx_corpNum = "";
        java.lang.String _getBankAccountLogEx_id = "";
        java.lang.String _getBankAccountLogEx_bankAccountNum = "";
        java.lang.String _getBankAccountLogEx_baseDate = "";
        int _getBankAccountLogEx_countPerPage = 0;
        int _getBankAccountLogEx_currentPage = 0;
        int _getBankAccountLogEx_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLogEx _getBankAccountLogEx__return = port.getBankAccountLogEx(_getBankAccountLogEx_certkey, _getBankAccountLogEx_corpNum, _getBankAccountLogEx_id, _getBankAccountLogEx_bankAccountNum, _getBankAccountLogEx_baseDate, _getBankAccountLogEx_countPerPage, _getBankAccountLogEx_currentPage, _getBankAccountLogEx_orderDirection);
        System.out.println("getBankAccountLogEx.result=" + _getBankAccountLogEx__return);


        }
        {
        System.out.println("Invoking getBankAccountLogURL...");
        java.lang.String _getBankAccountLogURL_certkey = "";
        java.lang.String _getBankAccountLogURL_corpNum = "";
        java.lang.String _getBankAccountLogURL_id = "";
        java.lang.String _getBankAccountLogURL_pwd = "";
        java.lang.String _getBankAccountLogURL__return = port.getBankAccountLogURL(_getBankAccountLogURL_certkey, _getBankAccountLogURL_corpNum, _getBankAccountLogURL_id, _getBankAccountLogURL_pwd);
        System.out.println("getBankAccountLogURL.result=" + _getBankAccountLogURL__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking getMonthlyBankAccountLogEx...");
        java.lang.String _getMonthlyBankAccountLogEx_certkey = "";
        java.lang.String _getMonthlyBankAccountLogEx_corpNum = "";
        java.lang.String _getMonthlyBankAccountLogEx_id = "";
        java.lang.String _getMonthlyBankAccountLogEx_bankAccountNum = "";
        java.lang.String _getMonthlyBankAccountLogEx_baseMonth = "";
        int _getMonthlyBankAccountLogEx_countPerPage = 0;
        int _getMonthlyBankAccountLogEx_currentPage = 0;
        int _getMonthlyBankAccountLogEx_orderDirection = 0;
        com.baroservice.ws.PagedBankAccountLogEx _getMonthlyBankAccountLogEx__return = port.getMonthlyBankAccountLogEx(_getMonthlyBankAccountLogEx_certkey, _getMonthlyBankAccountLogEx_corpNum, _getMonthlyBankAccountLogEx_id, _getMonthlyBankAccountLogEx_bankAccountNum, _getMonthlyBankAccountLogEx_baseMonth, _getMonthlyBankAccountLogEx_countPerPage, _getMonthlyBankAccountLogEx_currentPage, _getMonthlyBankAccountLogEx_orderDirection);
        System.out.println("getMonthlyBankAccountLogEx.result=" + _getMonthlyBankAccountLogEx__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking refreshBankAccount...");
        java.lang.String _refreshBankAccount_certkey = "";
        java.lang.String _refreshBankAccount_corpNum = "";
        java.lang.String _refreshBankAccount_id = "";
        java.lang.String _refreshBankAccount_bankAccountNum = "";
        int _refreshBankAccount__return = port.refreshBankAccount(_refreshBankAccount_certkey, _refreshBankAccount_corpNum, _refreshBankAccount_id, _refreshBankAccount_bankAccountNum);
        System.out.println("refreshBankAccount.result=" + _refreshBankAccount__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
