
package com.baroservice.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-11-25T11:59:31.360+09:00
 * Generated source version: 3.2.6
 *
 */
public final class BaroServiceSMSSoap_BaroServiceSMSSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.baroservice.com/", "BaroService_SMS");

    private BaroServiceSMSSoap_BaroServiceSMSSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BaroServiceSMS.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        BaroServiceSMS ss = new BaroServiceSMS(wsdlURL, SERVICE_NAME);
        BaroServiceSMSSoap port = ss.getBaroServiceSMSSoap12();

        {
        System.out.println("Invoking getSMSSendMessagesByRefKey...");
        java.lang.String _getSMSSendMessagesByRefKey_certkey = "";
        java.lang.String _getSMSSendMessagesByRefKey_corpNum = "";
        java.lang.String _getSMSSendMessagesByRefKey_refKey = "";
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessagesByRefKey__return = port.getSMSSendMessagesByRefKey(_getSMSSendMessagesByRefKey_certkey, _getSMSSendMessagesByRefKey_corpNum, _getSMSSendMessagesByRefKey_refKey);
        System.out.println("getSMSSendMessagesByRefKey.result=" + _getSMSSendMessagesByRefKey__return);


        }
        {
        System.out.println("Invoking changeCorpManager...");
        java.lang.String _changeCorpManager_certkey = "";
        java.lang.String _changeCorpManager_corpNum = "";
        java.lang.String _changeCorpManager_newManagerID = "";
        int _changeCorpManager__return = port.changeCorpManager(_changeCorpManager_certkey, _changeCorpManager_corpNum, _changeCorpManager_newManagerID);
        System.out.println("changeCorpManager.result=" + _changeCorpManager__return);


        }
        {
        System.out.println("Invoking sendMMSMessageFromFTP...");
        java.lang.String _sendMMSMessageFromFTP_certkey = "";
        java.lang.String _sendMMSMessageFromFTP_corpNum = "";
        java.lang.String _sendMMSMessageFromFTP_senderID = "";
        java.lang.String _sendMMSMessageFromFTP_fromNumber = "";
        java.lang.String _sendMMSMessageFromFTP_toName = "";
        java.lang.String _sendMMSMessageFromFTP_toNumber = "";
        java.lang.String _sendMMSMessageFromFTP_txtSubject = "";
        java.lang.String _sendMMSMessageFromFTP_txtmessage = "";
        java.lang.String _sendMMSMessageFromFTP_imageFileName = "";
        java.lang.String _sendMMSMessageFromFTP_sendDT = "";
        java.lang.String _sendMMSMessageFromFTP_refKey = "";
        java.lang.String _sendMMSMessageFromFTP__return = port.sendMMSMessageFromFTP(_sendMMSMessageFromFTP_certkey, _sendMMSMessageFromFTP_corpNum, _sendMMSMessageFromFTP_senderID, _sendMMSMessageFromFTP_fromNumber, _sendMMSMessageFromFTP_toName, _sendMMSMessageFromFTP_toNumber, _sendMMSMessageFromFTP_txtSubject, _sendMMSMessageFromFTP_txtmessage, _sendMMSMessageFromFTP_imageFileName, _sendMMSMessageFromFTP_sendDT, _sendMMSMessageFromFTP_refKey);
        System.out.println("sendMMSMessageFromFTP.result=" + _sendMMSMessageFromFTP__return);


        }
        {
        System.out.println("Invoking sendLMSMessage...");
        java.lang.String _sendLMSMessage_certkey = "";
        java.lang.String _sendLMSMessage_corpNum = "";
        java.lang.String _sendLMSMessage_senderID = "";
        java.lang.String _sendLMSMessage_fromNumber = "";
        java.lang.String _sendLMSMessage_toName = "";
        java.lang.String _sendLMSMessage_toNumber = "";
        java.lang.String _sendLMSMessage_subject = "";
        java.lang.String _sendLMSMessage_contents = "";
        java.lang.String _sendLMSMessage_sendDT = "";
        java.lang.String _sendLMSMessage_refKey = "";
        java.lang.String _sendLMSMessage__return = port.sendLMSMessage(_sendLMSMessage_certkey, _sendLMSMessage_corpNum, _sendLMSMessage_senderID, _sendLMSMessage_fromNumber, _sendLMSMessage_toName, _sendLMSMessage_toNumber, _sendLMSMessage_subject, _sendLMSMessage_contents, _sendLMSMessage_sendDT, _sendLMSMessage_refKey);
        System.out.println("sendLMSMessage.result=" + _sendLMSMessage__return);


        }
        {
        System.out.println("Invoking checkCorpIsMember...");
        java.lang.String _checkCorpIsMember_certkey = "";
        java.lang.String _checkCorpIsMember_corpNum = "";
        java.lang.String _checkCorpIsMember_checkCorpNum = "";
        int _checkCorpIsMember__return = port.checkCorpIsMember(_checkCorpIsMember_certkey, _checkCorpIsMember_corpNum, _checkCorpIsMember_checkCorpNum);
        System.out.println("checkCorpIsMember.result=" + _checkCorpIsMember__return);


        }
        {
        System.out.println("Invoking cancelReservedSMSMessageByReceiptNum...");
        java.lang.String _cancelReservedSMSMessageByReceiptNum_certkey = "";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_corpNum = "";
        java.lang.String _cancelReservedSMSMessageByReceiptNum_receiptNum = "";
        int _cancelReservedSMSMessageByReceiptNum__return = port.cancelReservedSMSMessageByReceiptNum(_cancelReservedSMSMessageByReceiptNum_certkey, _cancelReservedSMSMessageByReceiptNum_corpNum, _cancelReservedSMSMessageByReceiptNum_receiptNum);
        System.out.println("cancelReservedSMSMessageByReceiptNum.result=" + _cancelReservedSMSMessageByReceiptNum__return);


        }
        {
        System.out.println("Invoking addUserToCorp...");
        java.lang.String _addUserToCorp_certkey = "";
        java.lang.String _addUserToCorp_corpNum = "";
        java.lang.String _addUserToCorp_memberName = "";
        java.lang.String _addUserToCorp_juminNum = "";
        java.lang.String _addUserToCorp_id = "";
        java.lang.String _addUserToCorp_pwd = "";
        java.lang.String _addUserToCorp_grade = "";
        java.lang.String _addUserToCorp_tel = "";
        java.lang.String _addUserToCorp_hp = "";
        java.lang.String _addUserToCorp_email = "";
        int _addUserToCorp__return = port.addUserToCorp(_addUserToCorp_certkey, _addUserToCorp_corpNum, _addUserToCorp_memberName, _addUserToCorp_juminNum, _addUserToCorp_id, _addUserToCorp_pwd, _addUserToCorp_grade, _addUserToCorp_tel, _addUserToCorp_hp, _addUserToCorp_email);
        System.out.println("addUserToCorp.result=" + _addUserToCorp__return);


        }
        {
        System.out.println("Invoking sendMessage...");
        java.lang.String _sendMessage_certkey = "";
        java.lang.String _sendMessage_corpNum = "";
        java.lang.String _sendMessage_senderID = "";
        java.lang.String _sendMessage_fromNumber = "";
        java.lang.String _sendMessage_toName = "";
        java.lang.String _sendMessage_toNumber = "";
        java.lang.String _sendMessage_contents = "";
        java.lang.String _sendMessage_sendDT = "";
        java.lang.String _sendMessage_refKey = "";
        java.lang.String _sendMessage__return = port.sendMessage(_sendMessage_certkey, _sendMessage_corpNum, _sendMessage_senderID, _sendMessage_fromNumber, _sendMessage_toName, _sendMessage_toNumber, _sendMessage_contents, _sendMessage_sendDT, _sendMessage_refKey);
        System.out.println("sendMessage.result=" + _sendMessage__return);


        }
        {
        System.out.println("Invoking updateUserInfo...");
        java.lang.String _updateUserInfo_certkey = "";
        java.lang.String _updateUserInfo_corpNum = "";
        java.lang.String _updateUserInfo_id = "";
        java.lang.String _updateUserInfo_memberName = "";
        java.lang.String _updateUserInfo_juminNum = "";
        java.lang.String _updateUserInfo_tel = "";
        java.lang.String _updateUserInfo_hp = "";
        java.lang.String _updateUserInfo_email = "";
        java.lang.String _updateUserInfo_grade = "";
        int _updateUserInfo__return = port.updateUserInfo(_updateUserInfo_certkey, _updateUserInfo_corpNum, _updateUserInfo_id, _updateUserInfo_memberName, _updateUserInfo_juminNum, _updateUserInfo_tel, _updateUserInfo_hp, _updateUserInfo_email, _updateUserInfo_grade);
        System.out.println("updateUserInfo.result=" + _updateUserInfo__return);


        }
        {
        System.out.println("Invoking getSMSSendMessages...");
        java.lang.String _getSMSSendMessages_certkey = "";
        java.lang.String _getSMSSendMessages_corpNum = "";
        com.baroservice.ws.ArrayOfString _getSMSSendMessages_sendKeyList = new com.baroservice.ws.ArrayOfString();
        com.baroservice.ws.ArrayOfSMSMessage _getSMSSendMessages__return = port.getSMSSendMessages(_getSMSSendMessages_certkey, _getSMSSendMessages_corpNum, _getSMSSendMessages_sendKeyList);
        System.out.println("getSMSSendMessages.result=" + _getSMSSendMessages__return);


        }
        {
        System.out.println("Invoking getSMSSendMessage...");
        java.lang.String _getSMSSendMessage_certkey = "";
        java.lang.String _getSMSSendMessage_corpNum = "";
        java.lang.String _getSMSSendMessage_sendKey = "";
        com.baroservice.ws.SMSMessage _getSMSSendMessage__return = port.getSMSSendMessage(_getSMSSendMessage_certkey, _getSMSSendMessage_corpNum, _getSMSSendMessage_sendKey);
        System.out.println("getSMSSendMessage.result=" + _getSMSSendMessage__return);


        }
        {
        System.out.println("Invoking getLoginURL...");
        java.lang.String _getLoginURL_certkey = "";
        java.lang.String _getLoginURL_corpNum = "";
        java.lang.String _getLoginURL_id = "";
        java.lang.String _getLoginURL_pwd = "";
        java.lang.String _getLoginURL__return = port.getLoginURL(_getLoginURL_certkey, _getLoginURL_corpNum, _getLoginURL_id, _getLoginURL_pwd);
        System.out.println("getLoginURL.result=" + _getLoginURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistDate...");
        java.lang.String _getCertificateRegistDate_certkey = "";
        java.lang.String _getCertificateRegistDate_corpNum = "";
        java.lang.String _getCertificateRegistDate__return = port.getCertificateRegistDate(_getCertificateRegistDate_certkey, _getCertificateRegistDate_corpNum);
        System.out.println("getCertificateRegistDate.result=" + _getCertificateRegistDate__return);


        }
        {
        System.out.println("Invoking checkSMSFromNumber...");
        java.lang.String _checkSMSFromNumber_certkey = "";
        java.lang.String _checkSMSFromNumber_corpNum = "";
        java.lang.String _checkSMSFromNumber_fromNumber = "";
        int _checkSMSFromNumber__return = port.checkSMSFromNumber(_checkSMSFromNumber_certkey, _checkSMSFromNumber_corpNum, _checkSMSFromNumber_fromNumber);
        System.out.println("checkSMSFromNumber.result=" + _checkSMSFromNumber__return);


        }
        {
        System.out.println("Invoking registSMSFromNumber...");
        java.lang.String _registSMSFromNumber_certkey = "";
        java.lang.String _registSMSFromNumber_corpNum = "";
        java.lang.String _registSMSFromNumber_fromNumber = "";
        int _registSMSFromNumber__return = port.registSMSFromNumber(_registSMSFromNumber_certkey, _registSMSFromNumber_corpNum, _registSMSFromNumber_fromNumber);
        System.out.println("registSMSFromNumber.result=" + _registSMSFromNumber__return);


        }
        {
        System.out.println("Invoking checkChargeable...");
        java.lang.String _checkChargeable_certkey = "";
        java.lang.String _checkChargeable_corpNum = "";
        int _checkChargeable_cType = 0;
        int _checkChargeable_docType = 0;
        int _checkChargeable__return = port.checkChargeable(_checkChargeable_certkey, _checkChargeable_corpNum, _checkChargeable_cType, _checkChargeable_docType);
        System.out.println("checkChargeable.result=" + _checkChargeable__return);


        }
        {
        System.out.println("Invoking getSMSSendMessagesByPaging...");
        java.lang.String _getSMSSendMessagesByPaging_certkey = "";
        java.lang.String _getSMSSendMessagesByPaging_corpNum = "";
        java.lang.String _getSMSSendMessagesByPaging_fromDate = "";
        java.lang.String _getSMSSendMessagesByPaging_toDate = "";
        int _getSMSSendMessagesByPaging_countPerPage = 0;
        int _getSMSSendMessagesByPaging_currentPage = 0;
        com.baroservice.ws.PagedSMSMessages _getSMSSendMessagesByPaging__return = port.getSMSSendMessagesByPaging(_getSMSSendMessagesByPaging_certkey, _getSMSSendMessagesByPaging_corpNum, _getSMSSendMessagesByPaging_fromDate, _getSMSSendMessagesByPaging_toDate, _getSMSSendMessagesByPaging_countPerPage, _getSMSSendMessagesByPaging_currentPage);
        System.out.println("getSMSSendMessagesByPaging.result=" + _getSMSSendMessagesByPaging__return);


        }
        {
        System.out.println("Invoking ping...");
        port.ping();


        }
        {
        System.out.println("Invoking cancelReservedSMSMessage...");
        java.lang.String _cancelReservedSMSMessage_certkey = "";
        java.lang.String _cancelReservedSMSMessage_corpNum = "";
        java.lang.String _cancelReservedSMSMessage_sendKey = "";
        int _cancelReservedSMSMessage__return = port.cancelReservedSMSMessage(_cancelReservedSMSMessage_certkey, _cancelReservedSMSMessage_corpNum, _cancelReservedSMSMessage_sendKey);
        System.out.println("cancelReservedSMSMessage.result=" + _cancelReservedSMSMessage__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmount...");
        java.lang.String _getBalanceCostAmount_certkey = "";
        java.lang.String _getBalanceCostAmount_corpNum = "";
        long _getBalanceCostAmount__return = port.getBalanceCostAmount(_getBalanceCostAmount_certkey, _getBalanceCostAmount_corpNum);
        System.out.println("getBalanceCostAmount.result=" + _getBalanceCostAmount__return);


        }
        {
        System.out.println("Invoking getBaroBillURL...");
        java.lang.String _getBaroBillURL_certkey = "";
        java.lang.String _getBaroBillURL_corpNum = "";
        java.lang.String _getBaroBillURL_id = "";
        java.lang.String _getBaroBillURL_pwd = "";
        java.lang.String _getBaroBillURL_togo = "";
        java.lang.String _getBaroBillURL__return = port.getBaroBillURL(_getBaroBillURL_certkey, _getBaroBillURL_corpNum, _getBaroBillURL_id, _getBaroBillURL_pwd, _getBaroBillURL_togo);
        System.out.println("getBaroBillURL.result=" + _getBaroBillURL__return);


        }
        {
        System.out.println("Invoking getMessagesByReceiptNum...");
        java.lang.String _getMessagesByReceiptNum_certkey = "";
        java.lang.String _getMessagesByReceiptNum_corpNum = "";
        java.lang.String _getMessagesByReceiptNum_receiptNum = "";
        com.baroservice.ws.ArrayOfSMSMessage _getMessagesByReceiptNum__return = port.getMessagesByReceiptNum(_getMessagesByReceiptNum_certkey, _getMessagesByReceiptNum_corpNum, _getMessagesByReceiptNum_receiptNum);
        System.out.println("getMessagesByReceiptNum.result=" + _getMessagesByReceiptNum__return);


        }
        {
        System.out.println("Invoking getErrString...");
        java.lang.String _getErrString_certkey = "";
        int _getErrString_errCode = 0;
        java.lang.String _getErrString__return = port.getErrString(_getErrString_certkey, _getErrString_errCode);
        System.out.println("getErrString.result=" + _getErrString__return);


        }
        {
        System.out.println("Invoking sendMessages...");
        java.lang.String _sendMessages_certkey = "";
        java.lang.String _sendMessages_corpNum = "";
        java.lang.String _sendMessages_senderID = "";
        int _sendMessages_sendCount = 0;
        boolean _sendMessages_cutToSMS = false;
        com.baroservice.ws.ArrayOfXMSMessage _sendMessages_messages = new com.baroservice.ws.ArrayOfXMSMessage();
        java.lang.String _sendMessages_sendDT = "";
        java.lang.String _sendMessages__return = port.sendMessages(_sendMessages_certkey, _sendMessages_corpNum, _sendMessages_senderID, _sendMessages_sendCount, _sendMessages_cutToSMS, _sendMessages_messages, _sendMessages_sendDT);
        System.out.println("sendMessages.result=" + _sendMessages__return);


        }
        {
        System.out.println("Invoking checkCERTIsValid...");
        java.lang.String _checkCERTIsValid_certkey = "";
        java.lang.String _checkCERTIsValid_corpNum = "";
        int _checkCERTIsValid__return = port.checkCERTIsValid(_checkCERTIsValid_certkey, _checkCERTIsValid_corpNum);
        System.out.println("checkCERTIsValid.result=" + _checkCERTIsValid__return);


        }
        {
        System.out.println("Invoking sendSMSMessage...");
        java.lang.String _sendSMSMessage_certkey = "";
        java.lang.String _sendSMSMessage_corpNum = "";
        java.lang.String _sendSMSMessage_senderID = "";
        java.lang.String _sendSMSMessage_fromNumber = "";
        java.lang.String _sendSMSMessage_toName = "";
        java.lang.String _sendSMSMessage_toNumber = "";
        java.lang.String _sendSMSMessage_contents = "";
        java.lang.String _sendSMSMessage_sendDT = "";
        java.lang.String _sendSMSMessage_refKey = "";
        java.lang.String _sendSMSMessage__return = port.sendSMSMessage(_sendSMSMessage_certkey, _sendSMSMessage_corpNum, _sendSMSMessage_senderID, _sendSMSMessage_fromNumber, _sendSMSMessage_toName, _sendSMSMessage_toNumber, _sendSMSMessage_contents, _sendSMSMessage_sendDT, _sendSMSMessage_refKey);
        System.out.println("sendSMSMessage.result=" + _sendSMSMessage__return);


        }
        {
        System.out.println("Invoking getCorpMemberContacts...");
        java.lang.String _getCorpMemberContacts_certkey = "";
        java.lang.String _getCorpMemberContacts_corpNum = "";
        java.lang.String _getCorpMemberContacts_checkCorpNum = "";
        com.baroservice.ws.ArrayOfContact _getCorpMemberContacts__return = port.getCorpMemberContacts(_getCorpMemberContacts_certkey, _getCorpMemberContacts_corpNum, _getCorpMemberContacts_checkCorpNum);
        System.out.println("getCorpMemberContacts.result=" + _getCorpMemberContacts__return);


        }
        {
        System.out.println("Invoking getSMSFromNumberURL...");
        java.lang.String _getSMSFromNumberURL_certkey = "";
        java.lang.String _getSMSFromNumberURL_corpNum = "";
        java.lang.String _getSMSFromNumberURL_id = "";
        java.lang.String _getSMSFromNumberURL_pwd = "";
        java.lang.String _getSMSFromNumberURL__return = port.getSMSFromNumberURL(_getSMSFromNumberURL_certkey, _getSMSFromNumberURL_corpNum, _getSMSFromNumberURL_id, _getSMSFromNumberURL_pwd);
        System.out.println("getSMSFromNumberURL.result=" + _getSMSFromNumberURL__return);


        }
        {
        System.out.println("Invoking getCertificateExpireDate...");
        java.lang.String _getCertificateExpireDate_certkey = "";
        java.lang.String _getCertificateExpireDate_corpNum = "";
        java.lang.String _getCertificateExpireDate__return = port.getCertificateExpireDate(_getCertificateExpireDate_certkey, _getCertificateExpireDate_corpNum);
        System.out.println("getCertificateExpireDate.result=" + _getCertificateExpireDate__return);


        }
        {
        System.out.println("Invoking updateUserPWD...");
        java.lang.String _updateUserPWD_certkey = "";
        java.lang.String _updateUserPWD_corpNum = "";
        java.lang.String _updateUserPWD_id = "";
        java.lang.String _updateUserPWD_newPWD = "";
        int _updateUserPWD__return = port.updateUserPWD(_updateUserPWD_certkey, _updateUserPWD_corpNum, _updateUserPWD_id, _updateUserPWD_newPWD);
        System.out.println("updateUserPWD.result=" + _updateUserPWD__return);


        }
        {
        System.out.println("Invoking getCashChargeURL...");
        java.lang.String _getCashChargeURL_certkey = "";
        java.lang.String _getCashChargeURL_corpNum = "";
        java.lang.String _getCashChargeURL_id = "";
        java.lang.String _getCashChargeURL_pwd = "";
        java.lang.String _getCashChargeURL__return = port.getCashChargeURL(_getCashChargeURL_certkey, _getCashChargeURL_corpNum, _getCashChargeURL_id, _getCashChargeURL_pwd);
        System.out.println("getCashChargeURL.result=" + _getCashChargeURL__return);


        }
        {
        System.out.println("Invoking getCertificateRegistURL...");
        java.lang.String _getCertificateRegistURL_certkey = "";
        java.lang.String _getCertificateRegistURL_corpNum = "";
        java.lang.String _getCertificateRegistURL_id = "";
        java.lang.String _getCertificateRegistURL_pwd = "";
        java.lang.String _getCertificateRegistURL__return = port.getCertificateRegistURL(_getCertificateRegistURL_certkey, _getCertificateRegistURL_corpNum, _getCertificateRegistURL_id, _getCertificateRegistURL_pwd);
        System.out.println("getCertificateRegistURL.result=" + _getCertificateRegistURL__return);


        }
        {
        System.out.println("Invoking updateCorpInfo...");
        java.lang.String _updateCorpInfo_certkey = "";
        java.lang.String _updateCorpInfo_corpNum = "";
        java.lang.String _updateCorpInfo_corpName = "";
        java.lang.String _updateCorpInfo_ceoName = "";
        java.lang.String _updateCorpInfo_bizType = "";
        java.lang.String _updateCorpInfo_bizClass = "";
        java.lang.String _updateCorpInfo_postNum = "";
        java.lang.String _updateCorpInfo_addr1 = "";
        java.lang.String _updateCorpInfo_addr2 = "";
        int _updateCorpInfo__return = port.updateCorpInfo(_updateCorpInfo_certkey, _updateCorpInfo_corpNum, _updateCorpInfo_corpName, _updateCorpInfo_ceoName, _updateCorpInfo_bizType, _updateCorpInfo_bizClass, _updateCorpInfo_postNum, _updateCorpInfo_addr1, _updateCorpInfo_addr2);
        System.out.println("updateCorpInfo.result=" + _updateCorpInfo__return);


        }
        {
        System.out.println("Invoking registCorp...");
        java.lang.String _registCorp_certkey = "";
        java.lang.String _registCorp_corpNum = "";
        java.lang.String _registCorp_corpName = "";
        java.lang.String _registCorp_ceoName = "";
        java.lang.String _registCorp_bizType = "";
        java.lang.String _registCorp_bizClass = "";
        java.lang.String _registCorp_postNum = "";
        java.lang.String _registCorp_addr1 = "";
        java.lang.String _registCorp_addr2 = "";
        java.lang.String _registCorp_memberName = "";
        java.lang.String _registCorp_juminNum = "";
        java.lang.String _registCorp_id = "";
        java.lang.String _registCorp_pwd = "";
        java.lang.String _registCorp_grade = "";
        java.lang.String _registCorp_tel = "";
        java.lang.String _registCorp_hp = "";
        java.lang.String _registCorp_email = "";
        int _registCorp__return = port.registCorp(_registCorp_certkey, _registCorp_corpNum, _registCorp_corpName, _registCorp_ceoName, _registCorp_bizType, _registCorp_bizClass, _registCorp_postNum, _registCorp_addr1, _registCorp_addr2, _registCorp_memberName, _registCorp_juminNum, _registCorp_id, _registCorp_pwd, _registCorp_grade, _registCorp_tel, _registCorp_hp, _registCorp_email);
        System.out.println("registCorp.result=" + _registCorp__return);


        }
        {
        System.out.println("Invoking getSMSHistoryURL...");
        java.lang.String _getSMSHistoryURL_certkey = "";
        java.lang.String _getSMSHistoryURL_corpNum = "";
        java.lang.String _getSMSHistoryURL_id = "";
        java.lang.String _getSMSHistoryURL_pwd = "";
        java.lang.String _getSMSHistoryURL__return = port.getSMSHistoryURL(_getSMSHistoryURL_certkey, _getSMSHistoryURL_corpNum, _getSMSHistoryURL_id, _getSMSHistoryURL_pwd);
        System.out.println("getSMSHistoryURL.result=" + _getSMSHistoryURL__return);


        }
        {
        System.out.println("Invoking sendMMSMessage...");
        java.lang.String _sendMMSMessage_certkey = "";
        java.lang.String _sendMMSMessage_corpNum = "";
        java.lang.String _sendMMSMessage_senderID = "";
        java.lang.String _sendMMSMessage_fromNumber = "";
        java.lang.String _sendMMSMessage_toName = "";
        java.lang.String _sendMMSMessage_toNumber = "";
        java.lang.String _sendMMSMessage_txtSubject = "";
        java.lang.String _sendMMSMessage_txtmessage = "";
        byte[] _sendMMSMessage_imageFile = new byte[0];
        java.lang.String _sendMMSMessage_sendDT = "";
        java.lang.String _sendMMSMessage_refKey = "";
        java.lang.String _sendMMSMessage__return = port.sendMMSMessage(_sendMMSMessage_certkey, _sendMMSMessage_corpNum, _sendMMSMessage_senderID, _sendMMSMessage_fromNumber, _sendMMSMessage_toName, _sendMMSMessage_toNumber, _sendMMSMessage_txtSubject, _sendMMSMessage_txtmessage, _sendMMSMessage_imageFile, _sendMMSMessage_sendDT, _sendMMSMessage_refKey);
        System.out.println("sendMMSMessage.result=" + _sendMMSMessage__return);


        }
        {
        System.out.println("Invoking getSMSSendState...");
        java.lang.String _getSMSSendState_certkey = "";
        java.lang.String _getSMSSendState_corpNum = "";
        java.lang.String _getSMSSendState_sendKey = "";
        int _getSMSSendState__return = port.getSMSSendState(_getSMSSendState_certkey, _getSMSSendState_corpNum, _getSMSSendState_sendKey);
        System.out.println("getSMSSendState.result=" + _getSMSSendState__return);


        }
        {
        System.out.println("Invoking getBalanceCostAmountOfInterOP...");
        java.lang.String _getBalanceCostAmountOfInterOP_certkey = "";
        long _getBalanceCostAmountOfInterOP__return = port.getBalanceCostAmountOfInterOP(_getBalanceCostAmountOfInterOP_certkey);
        System.out.println("getBalanceCostAmountOfInterOP.result=" + _getBalanceCostAmountOfInterOP__return);


        }
        {
        System.out.println("Invoking getChargeUnitCost...");
        java.lang.String _getChargeUnitCost_certkey = "";
        java.lang.String _getChargeUnitCost_corpNum = "";
        int _getChargeUnitCost_chargeCode = 0;
        int _getChargeUnitCost__return = port.getChargeUnitCost(_getChargeUnitCost_certkey, _getChargeUnitCost_corpNum, _getChargeUnitCost_chargeCode);
        System.out.println("getChargeUnitCost.result=" + _getChargeUnitCost__return);


        }

        System.exit(0);
    }

}
